- docs/react-testing-library/api.md
While I was reading the API documentation about react-testing-library, I noticed this small typo that can lead to errors when copy-pasted.
Thanks for this lib and doc 😉
> Typo in react-testing-library API

- docs/react-testing-library/setup.md
With the Jest 24 release, they've deprecated `setupTestFrameworkScriptFile` in favor of [`setupFilesAfterEnv`](https://jestjs.io/docs/en/configuration.html#setupfilesafterenv-array), so I thought it would be helpful to update the docs to match.
> setupTestFrameworkScriptFile => setupFilesAfterEnv

- docs/react-testing-library/api.md
Hi! :wave: 
Currently, the `See examples page` [here](https://testing-library.com/docs/react-testing-library/api#rerender) is linking to the wrong document. This PR fixes it.
Cheers and thanks for the docs. :smiley:
> Fix link to the Update Props page

- docs/api-helpers.md
- docs/api-queries.md
Closes #25 
@gregtatum how does this look? Made the the different types of queries a top-level section and added searchable text for each query name.
> Reorganize query documentation

- docs/react-testing-library/api.md
- docs/react-testing-library/setup.md
- Adds docs for render option "wrapper": https://github.com/kentcdodds/react-testing-library/pull/303
- Reorganizes the API and Setup pages for rtl slightly to add better heading structure for the right navbar.
Accidentally got remotes mixed up - this reverts the revert that prematurely merged the change.
This reverts commit c47aae0c8b92b71be73ac64cda0453f13c434642.
> feat(render): options.wrapper api + customRender usage

- docs/react-testing-library/api.md
Currently the anchor link for `render` navigates to `act`. See example [here](https://testing-library.com/docs/react-testing-library/api). This PR fixes this issue.
> fix anchor link for render

- docs/react-testing-library/api.md
There's no anchor called '#guiding-principles' in this page.
It should take us to the page, '/guiding-principles'.
> Broken link

- docs/react-testing-library/faq.md
Fix broken links in react-testing-library FAQ, under the "If I can't use shallow rendering, how do I mock out components in tests?" section.
Issue: https://github.com/kentcdodds/react-testing-library/issues/321
> Fix react-testing-library FAQ broken links (#321)

- .vscode/markdown.code-snippets
- .vscode/settings.json
- docs/api-configuration.md
- docs/api-helpers.md
- docs/api-queries.md
- docs/react-testing-library/api.md
- website/blog/2018-12-29-new-site.md
- website/blog/2019-03-17-code-blocks.md
- website/package.json
- website/static/css/custom.css
> add code for different wrappers on query api page

- docs/api-queries.md
Reference https://github.com/kentcdodds/dom-testing-library/pull/224
> docs: add `findBy` query type docs.

- website/sidebars.json
Hi friends,
I noticed when I was going through the docs, if you're on `/docs/example-reach-router` and you clicked the next button, you'd be lead to the 404 page. But clicking on `External Examples` in the sidebar brought you to the next page following the `Reach Router` example.
I took a look at the code and it looks like `example-reach-transition-group` is not a thing anymore. So I figured `example-reach-transition-group` might just be a dangling piece of code in `sidebars.json` and removed it.
Seems to do the trick. In the `Reach Router` doc the next button now takes the user to the expected `External Examples`.
**Button before:**
**Button after change:**
> Removed dangling 'example-reach-transition-group' example from sidebar

- docs/dom-testing-library/cheatsheet.md
- docs/react-testing-library/cheatsheet.md
I noticed a few typos in the react-testing-library cheatsheet page.  For the https://testing-library.com/docs/react-testing-library/cheatsheet#queries section the **ByTestId** displays a copy of the placeholder content above it.
This PR updates these values to their correct naming.
> Update react-testing-library cheatsheet typos

- docs/dom-testing-library/cheatsheet.md
thanks for accepting my previous PR. I missed a typo in one of the links. This fixes the typo.
> fix typo in link on dom-testing-library/cheatsheet.md

- website/siteConfig.js
As discussed in issue #93 
I have removed the duplicate call to the css `code-block-buttons.css` as it was giving a 404 error in browser console after compiling.
the above mentioned css is compiled and already a part of `main.css` and hence the call was duplicate and therefore is being removed here.
Before:
After:
/cc: @alexkrolick 
(Fixes #93)
> Removed duplicate call to code-block-buttons.css in siteConfig.js

- .all-contributorsrc
As discussed in #78 
After merging of one contribution, The .all-contributorsrc file now follows the same convention as that of all other projects in testing-library.
I feel this will be sufficient for the setup and we can after this merge setup the issue which we can dedicate to add contributors. 🥇 
/cc: @alexkrolick
> Fixing .all-contributorsrc to work similar to rest of the projects.

- docs/dom-testing-library/api-events.md
Added documentation for `createEvent` introduced in this PR https://github.com/testing-library/dom-testing-library/pull/258
> Add documentation for createEvent

- docs/svelte-testing-library/intro.md
This should be merged after https://github.com/testing-library/svelte-testing-library/pull/24 will be published
cc @benmonro
> Added example for container

- docs/dom-testing-library/api-queries.md
Fixes #116
I replaced `/incredibles.*png$/i` with `'Incredibles 2 Poster'`, which should match the `alt` attribute in the example markup.
> Fix `getByAltText` examples

- docs/vue-testing-library/intro.md
Hi! 
I noticed a few outdated links and also quick wins in vue-testing-library page, so here's a PR.
btw, this page and `vue-testing-library` README are so similar. Does it make sense? Should the page on testing-library.com contain different information from the README on GitHub?
Thank you all for your work in this project.
> Update vue-testing-library page

- docs/ecosystem-react-select-event.md
- website/sidebars.json
https://github.com/romgain/react-select-event/issues/2
> Add a reference to react-select-event

- docs/native-testing-library/intro.md
I was reading the React Native docs and spotted a typo - this PR fixes this 👍
> Fix Typo In Native Docs

- docs/vue-testing-library/api.md
- docs/vue-testing-library/examples.md
- docs/vue-testing-library/intro.md
- docs/vue-testing-library/setup.md
- website/sidebars.json
As discussed [here](https://github.com/testing-library/vue-testing-library/issues/33), I'm submitting a PR to extend Vue Testing Library docs.
There's a lot of content, so feel free to suggest any modification, clarification or addition! I tried to use as many bits from DOM/React Testing Library as possible.
Thanks!
> Add improved Vue docs

- docs/testcafe-testing-library/intro.md
Removed since the [issue](https://github.com/DevExpress/testcafe/issues/3758) was already resolved.
> Remove Known Issue section from testcafe-testing-library intro

- docs/cypress-testing-library/intro.md
Edited README only.
Why?
I followed the instructions and it didn't work with recent changes to official instructions from Cypress-typescript I installed last week. So these documentation will help out anyone doing this today.
I also found the types file to be handy for all library definitions, so I added it into the README
> 📝 Add correct tsconfig instructions for cypress

- docs/react-testing-library/api.md
This PR fixes some typos that I've found in the doc.
> Fix some typos

- docs/react-testing-library/api.md
I was looking at adding a custom data attribute query and found these docs, but RTL doesn't contain a default export so importing queries as in the example doesn't work. Just added a quick fix for the import.
> docs: fix import in render function queries option example

- docs/marko-testing-library/api.md
- docs/marko-testing-library/intro.md
- docs/marko-testing-library/setup.md
- website/sidebars.json
This PR adds documentation for the new [`@marko/testing-library`](https://github.com/marko-js/testing-library) and closes https://github.com/testing-library/dom-testing-library/issues/290.
The above package is unreleased, but is ready to go hopefully along side this additional documentation!
Any feedback is much appreciated 😄
> docs: add marko testing library

- docs/dom-testing-library/api-helpers.md
- docs/react-testing-library/setup.md
Following on from my previous PR (#151) and having noticed the discussion in #80:
* Adding an example for adding custom queries globally via creating a custom render function.
In the example, I've create a data attribute selector for `data-cy` as this is one of the attributes recommended by Cypress. I think in reality I would favour replacing `data-cy` globally throughout my projects with `data-testid`, but this may be useful for some people not willing to refactor out `data-cy`, or similar, at the moment.
> docs: add custom queries example to custom render docs

- docs/react-testing-library/setup.md
Fixing a few typos on the new custom queries section.
> docs: fix typos in custom queries section

- docs/react-testing-library/cheatsheet.md
Hi! 👋 
AFAIK, RTL automatically binds the queries' first argument to baseElement (`document.body` by default), so there's no need to specify a container.
thx!
> Remove non-existent parameter from getByText

- docs/example-react-redux.md
The previous example put all the necessary variables into one "file" (code block). However, this is unrealistic, and I found it confusing when first reading through the docs.
Instead, I've broken each chunk of this example into its own "file", which I think reads better and will be more applicable to a user's code base.
> Break React-Redux example into multiple "files" (code blocks)

- docs/dom-testing-library/api-queries.md
Changed the TextMatch from `username` to `Username` in the `getByLabelText()` example.
I believe the method uses exact match by default, which would make the test fail as the label it is looking for has a value of `Username`.
> Fix a capitalization error

- docs/dom-testing-library/api-queries.md
Closes testing-library/dom-testing-library#302
> Document default aria roles consideration

- docs/dom-testing-library/cheatsheet.md
- docs/guide-events.md
- website/sidebars.json
Closes testing-library/dom-testing-library#293, testing-library/dom-testing-library#292
[View rendered text](https://deploy-preview-172--testing-library.netlify.com/docs/guide-events)
> Add guide for events

- docs/dom-testing-library/api-helpers.md
This PR intends to add documentation on the missing `options` parameter of [prettyDOM](https://testing-library.com/docs/dom-testing-library/api-helpers#prettydom).
It closes #178.
- Specify that `prettyDOM` is built on top of `pretty-format`
- Add the missing type of `prettyDOM`
- Explains what `options` refers to
> Add docs on prettyDOM options parameter

- docs/react-testing-library/faq.md
- website/static/css/custom.css
hovering over each question in the faq, results in the cursor changing to a text cursor. I have added a simply style attribute of pointer: cursor and id to each summary.
> change text cursor to pointer cursor

- docs/react-testing-library/api.md
All other examples are using hooks, so I refactored this one to use hooks too.
> refactoring asFragment example to use hooks

- netlify.toml
Since a lot of people are committing on GitHub directly, there are lots of pages that haven't had the format command run over them. This PR adds the format command before pushing to netlify. This won't check in changes, but it will catch formatting inconsistency in code blocks when published.
> run format command before build for consistency

- docs/dom-testing-library/api-queries.md
- docs/marko-testing-library/intro.md
- docs/vue-testing-library/intro.md
A couple of pages still refer to Guiding Principles as if they are sections on the same page.
* https://testing-library.com/docs/dom-testing-library/api-queries#bytestid
* https://testing-library.com/docs/marko-testing-library/intro
This PR fixes broken links and also tweaks one more link to make all paths to `guiding-principles.md` consistent. ✌️
> Fix links to guiding-principles.md

- netlify.toml
Today I wanted to share DTL docs, only to realize that the http://testing-library.com/dom redirect isn't set.
> Add /dom redirect

- docs/react-testing-library/example-intro.md
- docs/svelte-testing-library/intro.md
**Please Review**
Searched for the ' _expect(container.firstChild).toMatchSnapshot()_ ' in the docs and found 2 examples.  Replaced both with ' _expect(container).toMatchSnapshot()_ '
> updated example code per issue

- docs/example-input-event.md
- docs/example-reach-router.md
- docs/example-react-context.md
- docs/example-react-hooks-useReducer.md
- docs/example-react-intl.md
- docs/example-react-redux.md
- docs/example-react-router.md
- docs/example-react-transition-group.md
- docs/example-update-props.md
- docs/react-testing-library/api.md
- docs/react-testing-library/example-intro.md
- docs/react-testing-library/faq.md
- docs/react-testing-library/setup.md
This pull request removes any instances of `cleanup-after-each` and `afterEach(cleanup)` in the react docs and examples. From issue #212
> Remove cleanup references

- docs/react-testing-library/example-intro.md
Replace `<button disabled >` with `<button disabled>`.
> Remove unnecessary whitespace in example-intro.md

- docs/cypress-testing-library/intro.md
Update cypress docs to match testing-library/cypress-testing-library#69
> Update cypress docs

- docs/dom-testing-library/install.md
Since react is a library not a framework, so it should be stated in the docs. Otherwise there is a chance of misconception.
> docs: update dom-testing-library/install.md to state react as library

- docs/react-testing-library/setup.md
One of the customRender examples is accepting an options argument but not passing it to the rtl render function. This just adds it in.
> docs: pass options into render function

- docs/vue-testing-library/setup.md
This PR resolves Issue #230 
With the deprecation of the `cleanup-after-each.js` the documentation should be updated to remove the section referring to it.`
> Remove deprecated Vue setup information

- docs/angular-testing-library/api.md
- docs/angular-testing-library/examples.md
- docs/angular-testing-library/intro.md
- website/sidebars.json
Adds documentation for Angular
- Wording on the introduction page to stay consistent with the other libraries
- API page
- Examples page - with reference to more examples in the angular repo
> docs(Angular): add examples and API

- docs/native-testing-library/intro.md
- docs/vue-testing-library/intro.md
Most of the libraries use `Introduction` in the sidebar, this PR updates the ones that were using `Intro`.
> docs: use introduction in the side bar

- docs/guide-events.md
Adds in missing parenthesis for `fireEvent.focus` example
> Adds in missing parenthesis for an example

- docs/react-testing-library/faq.md
This has comes up every so often in issues and Spectrum, so I've tried to summarize the cause & resolutions available.
> Add FAQ about "update not wrapped in act" warnings

- docs/dom-testing-library/api-events.md
When using `fireEvent.keyDown` the `event.which` value is a fallback of `0` unless the `keyCode` is passed. I thought this might be helpful for other folks trying the same.
e.g.
```js
fireEvent.keyDown(domNode, { key: 'Enter', code: 13, charCode: 13 }); // event.which => 0
fireEvent.keyDown(domNode, { key: 'Enter', keyCode: 13 }); // event.which => 13
```
> Update events doc for event.which usage on keyboard events

- docs/example-react-router.md
- extract out "renderWithRouter" helper and explain when it is needed
- add some "getBy" queries instead of just container.innerHTML assertions, to show more idiomatic RTL usage
> docs(react-router): examples for react-router

- docs/cypress-testing-library/intro.md
Hi, I explained the problem at issue #269 
So I tried to change the URL right place and change examples in there. But I'm not sure if my example is correct.
I look forward to hearing from you.
Thanks
> Fix Cypress example URL and example in cypress-testing-library/intro.md

- docs/dom-testing-library/faq.md
I added a note to the main FAQ about accessing the component instance and redirect the user to the guiding-principles of the library.
This is in reference to this tweet from Kent: https://twitter.com/kentcdodds/status/1179390041031892995
> Add note about component instance and methods to main FAQ

- docs/dom-testing-library/api-queries.md
I find quite handy the [list of HTML elements mapped to roles from aria-query](https://github.com/A11yance/aria-query#elements-to-roles) and I usually go there for finding available roles for HTML Elements, so I think it would be a nice addition to have proper reference to that documentation within `ByRole` doc (apart from the fact that DOM Testing Library uses aria-query)
> docs: add aria-query doc link to ByRole query

- docs/dom-testing-library/api-helpers.md
Documentation for https://github.com/testing-library/dom-testing-library/pull/364
> feat: Add isInaccessible

- docs/ecosystem-user-event.md
The example code was destructuring `getByText` instead of `getByTestId` which is what is used later. Also, moved `test` to wrap the code right and changed it's name.
> Fix user-event example

- docs/dom-testing-library/api-configuration.md
`configure` is exported from `@testing-library/cypress` as of https://github.com/testing-library/cypress-testing-library/pull/81 / version 4.2.0
Update documentation to describe `configure` usage with cypress.
> Update cypress configure documentation

- docs/native-testing-library/setup.md
the preset name was wrong, probably a bad replace  somewhere?
> Documentation: native-testing-library fix preset name

- docs/dom-testing-library/api-queries.md
- docs/dom-testing-library/faq.md
- docs/ecosystem-user-event.md
- docs/guide-which-query.md
- docs/react-testing-library/example-intro.md
- docs/vue-testing-library/cheatsheet.md
This is a collection of changes that tries to reduce the amount of `byTestId` usages.
`byTestId` is especially problematic for component libraries since the markup is very often not simple (e.g. includes wrapper divs) and users often ask where they should put the testId or claim the library in question is not very well testable with `@testing-library/*`. 
In many cases a `byRole` query would have resolved those questions.
It is probably a good idea to also add a table to the docs explaining which HTML elements map to which ARIA role. I'd like to to do this in a separate PR since there are some unresolved issues with `aria-query` and we need to figure out where the source of truth is (aria-query or html-aam).
> docs: Prefer byRole over byTestId where possible

- docs/dom-testing-library/api-helpers.md
I found a typo in the example output under the [Debugging section](https://testing-library.com/docs/dom-testing-library/api-helpers#debugging).
Given our element is
```html
<div>Hello world</div>
```
The `container` output should be
```html
<div>
<div>
Hello world
</div>
</div>
```
instead of
```html
<div>
<div>
Hello World!
</div>
</div>
```
---
The PR also fixes some small capitalization errors.
> fix: typos in debugging example

- docs/example-react-redux.md
- docs/example-react-router.md
Use extend-expect to improve the examples.
Additionally, `@testing-library-react` was imported in the wrong file.
> Enhance react examples

- docs/vue-testing-library/api.md
- docs/vue-testing-library/cheatsheet.md
- docs/vue-testing-library/examples.md
`cleanup()` is automatically run `afterEach` hook, so there's no need to suggest adding it by default.
> Remove cleanup() references from Vue docs

- docs/dom-testing-library/api-events.md
I found some typos in the `api-events` article.
> docs(api-events): Fix some typos

- docs/dom-testing-library/api-configuration.md
I was a bit confused while reading through these docs as to whether or not the value I supplied to `testIdAttribute` would be prefixed with `data-`. It turns out that the value is _not_ prefixed, and so `my-data-test-id` wouldn't be a valid `data-` attribute. This change replaces the current example `my-data-test-id` with `data-my-test-id`. I think this makes this example more clear.
> Clarify testIdAttribute

- docs/svelte-testing-library/api.md
- docs/svelte-testing-library/example.md
ref: https://github.com/testing-library/svelte-testing-library/pull/62
> docs(svelte): props can now be passed in directly

- docs/react-testing-library/example-intro.md
This code does not work without specifically instructing the manual mock.
It is only the case while automock is set to false (as it is by default, and create-react-app does not support overriding it)
> add jest.mock() instruction

- docs/cypress-testing-library/intro.md
This update brings the Cypress Testing Library documentation to be better in line with the current README of the project. It also removes references to the `get*` queries as there were [removed in v5](https://github.com/testing-library/cypress-testing-library/releases/tag/v5.0.0).
> update Cypress documentation for v5

- docs/dom-testing-library/api-queries.md
ref: https://github.com/testing-library/dom-testing-library/pull/412
> add "screen" docs

- docs/example-react-modal.md
This PR changes the example such that the component has the name that is referenced in the test.
> Fix component name: from App to Modal

- docs/ecosystem-jest-dom.md
People not familiar with jest matchers extensions might not know what to do after installing the lib, so this addition should avoid confusion.
> Improve usage instructions for jest-dom

- docs/cypress-testing-library/intro.md
Currently, the hyperlink attached to `See the DOM Testing Library docs for reference` takes you to `testing-library`'s home page (`testing-library.com`). It makes more sense (for the given text) to link to the DOM Testing Library API docs, in my opinion.
> Update Cypress intro.md

- docs/vue-testing-library/examples.md
See also: https://github.com/testing-library/vue-testing-library\#more-examples
> docs: add missing examples for vue-testing-library

- docs/cypress-testing-library/intro.md
Recently https://github.com/testing-library/cypress-testing-library/pull/108 added a way to take the previous subject of a previous command to scope the query. Also `find*` queries handle `.should('not.exist')` and should be preferred over `query*` which require additional logic for eventual non-existence queries.
> docs: Update Cypress Testing Library scoping example

- docs/dom-testing-library/api-queries.md
Using the current command throws with
> Error: You used 'getByLabelText' which has been removed from Cypress Testing Library because it does not make sense in this context. Please use 'findByLabelText' instead.
This PR changes the command to `findByLabelText` as recommended by the error message
> Update Cypress documentation reference from getByLabelText to findByLabelText

- docs/dom-testing-library/api-queries.md
- docs/guide-which-query.md
Docs for https://github.com/testing-library/dom-testing-library/pull/408
Preview:
- https://deploy-preview-368--testing-library.netlify.com/docs/dom-testing-library/api-queries#byrole
- https://deploy-preview-368--testing-library.netlify.com/docs/guide-which-query
I moved `byRole` up in the recommendations. I'm not so sure if we should already do this though. Personally I would hope that we can reduce the queries to `byRole` and `byTestId` and then recommend asserting properties such as `placeholder`, `alt`, `value` etc. Choosing the right query is currently not trivial. Though I fear that by only having `byRole` we loose a lot of people because they are not aware of the role names and fall back to testid. While I would hope that everybody knows what roles are it's not mainstream …
> feat(byRole): Add `name` option

- docs/react-testing-library/intro.md
`for elements` --> `form elements`
> docs(intro): fix typo in solution section

- docs/dom-testing-library/api-helpers.md
The `console.log` is redundant, may as well remove it 😄.
> docs: remove `console.log` from `logRoles` example

- docs/guide-disappearance.md
Update to mention `waitFor` as it will replace `wait` and change `waitForElement` example to use `findBy` query instead.
> Update guide-disappearance to mention waitFor and change waitForElement to findBy

- docs/testcafe-testing-library/intro.md
Module is preferable to absolute file path as it doesn't assume the location of `node_modules` folder and works better with monorepos using yarn workspaces etc. where dependencies may be hoiseted.
This `{ "module": "npm module" }` syntax is documented here https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html#clientscripts — see the example of how `"loadsh"` is loaded.
> Updates clientScript instructions to use module

- docs/react-testing-library/example-intro.md
Replace waitForElement to WaitFor to break warnings on console and update example-intro on https://testing-library.com/docs/react-testing-library/example-intro 
And set correctly use guide to o use new release.
> Replace waitForElement to waitFor to remove warnings 

- docs/dom-testing-library/example-intro.md
- docs/example-react-router.md
- docs/pptr-testing-library/intro.md
https://github.com/testing-library/dom-testing-library/releases
> Sync docs with latest dom-testing-library

- docs/dom-testing-library/api-events.md
In this section of the DOM Testing Library docs for `fireEvent`: https://testing-library.com/docs/dom-testing-library/api-events#fireeventeventname
It seems like the link to the event options goes to a different place than intended.
Link before: https://github.com/testing-library/dom-testing-library/blob/master/src/events.js
Link with this PR: https://github.com/testing-library/dom-testing-library/blob/master/src/event-map.js
> docs: Fix event link to event map file

- docs/dom-testing-library/api-queries.md
findBy / findAllBy default timeout is 1000ms and not 450ms
see: 
https://github.com/testing-library/dom-testing-library/blob/1b711a4a0143b532dc8258f9ceac1a1b36557ce0/src/config.js#L8
https://github.com/testing-library/dom-testing-library/blob/672f2316d49609572857e7de80251eb052c9cbd1/src/wait-for.js#L15
Thanks for your awesome work!
> findBy / findAllBy default timeout

- docs/example-react-redux.md
Updated the React Redux recipe to use a custom `render` with the `wrapper` option.
Also refactored the class component to a functional component.
This PR is following the talk with @kentcdodds in [this](https://github.com/reduxjs/redux/pull/3708) PR.
> Update React Redux recipe to use custom render with wrapper

- docs/example-react-redux.md
I saw that accidentally I kept an empty import in the code and didn't use the new `render` function,
Fixed that.
> Fix: Remove the unnecessary empty import and use the correct render function

- docs/dom-testing-library/api-async.md
added information for anyone trying to migrate an existing parameterless wait call. Also there were 2 headings for wait() and I removed the second one because I thought it was superfluous
> explain how to update wait to waitFor

- docs/dom-testing-library/api-queries.md
This is recommended and works better across framework implementations so there should be less confusion.
> Update all query references to screen

- docs/dom-testing-library/api-async.md
Updating the example description as the previous example given for `waitFor` doesn't match the old description.
> Documentation correction for new async utility waitFor

- docs/react-testing-library/setup.md
that can still cause a lot of confusion :)
it should be (only one dot)
```js 
"test-utils": ["./utils/test-utils"]
```
instead of 
```js 
"test-utils": ["../utils/test-utils"]
```
> fixed a minor typo

- docs/ecosystem-user-event.md
Made the change in the demo here https://testing-library.com/docs/ecosystem-user-event
```diff
- userEvent.type(getByRole('textbox'), 'Hello, World!')
+ await userEvent.type(getByRole('textbox'), 'Hello, World!')
```
> [docs] add await to example in userEvent.type for page example in testing-library.com/docs/ecosystem-user-event

- docs/react-testing-library/example-intro.md
Found a small typo in the example code when working through the React tutorial
> fixed example code typo

- docs/dom-testing-library/api-queries.md
Docs for https://github.com/testing-library/dom-testing-library/pull/540
> docs(ByRole): Add { selected: boolean } option

- docs/dom-testing-library/api-events.md
Docs for https://github.com/testing-library/dom-testing-library/pull/554
Please let me know if there is anywhere else that might be worth documenting this change. Also feel free to edit and improve.
> docs: add dataTransfer event property info

- docs/dom-testing-library/api-queries.md
fix  getByAltText function name
> docs(api-queries): Fix getByAltText function name

- docs/example-codesandbox.md
- docs/example-external.md
- docs/guide-which-query.md
As talked about on [Twitter](https://twitter.com/TestingLib/status/1262764875127742466?s=20), I've added a link to [testing-playground.com](https://testing-playground.com) to the docs. I've done this in three different places. Feel free to correct me in case I've taken the `somewhere where people won't miss it` a bit too literally :innocent: 
I've also thought about adding a link to the footer or sidebar instead, but it didn't really match there with anything else. Let me know if you think otherwise. The docs are huge! (which is a good thing), so this is a long shot, which I'm sure can be improved.
Anyways, what I've done:
**Added**:
> **Playground**
> 
> Are you looking for a quick way to run queries against your own html instead? Try …
> docs: add links to testing-playground.com

- docs/react-testing-library/faq.md
As a new user of this library I had a difficult time determining how to test outcomes of a drop-down selection.  There is an example if you use the react-select library but very little information on the internet if you use a plain select tag.
I found Kent's comment on an issue in the react-testing-library and thought it would be helpful to others to add it to the FAQs.  https://github.com/testing-library/react-testing-library/issues/322
> Add example of firing select event

- docs/dom-testing-library/api-queries.md
This PR adds a comma to the subtitle in the ByLabelText section after the queryAllByLabelText
> Adds comma to the subtitle in the ByLabelText section

- docs/angular-testing-library/api.md
- docs/angular-testing-library/examples.md
- updates the docs for the v9 version
- uses `screen` in the examples
- add a note about the patched re-exports
> docs(angular): update to latest version

- docs/react-testing-library/example-intro.md
- Removes the usage of `jest.mock` and `axiosMock.get.mockResolvedValueOnce()` in favor of a more declarative approach (see the reasoning in the GitHub issue).
- Updates the "Step-by-step" section to briefly explain why `msw` has been added, and what each of its usage steps means.
- Closes #482 
This was the only usage example I've found that illustrates testing a component that performs requests. Please, if I missed something, would you suggest me where to look for similar examples in the documentation? Thanks!
> docs: replace "axiosMock" with "msw" in React Testing Library example

- docs/vue-testing-library/faq.md
The link to stub example in [FAQ page](https://testing-library.com/docs/vue-testing-library/faq) of VTL is broken. It links to a 404 page now.
I think you want to link to stubs.js in https://github.com/testing-library/vue-testing-library/blob/master/src/__tests__/stubs.js. Therefore, I change to the link to that file.
> docs(vue-testing-library): fix broken stub example link in VTL docs

- docs/testcafe-testing-library/intro.md
This [supporting code](https://testing-library.com/docs/testcafe-testing-library/intro#globally-for-all-fixtures-tests-and-page-loads-by-injecting-clientscriptsinject) that helps explain working with Testcafe is missing a comma.
Please note, while my change only added the missing `,` it appears as if husky pre-commit formatted this file.
> Docs: Adds comma to testcafe example code

- docs/react-testing-library/example-intro.md
Thanks for the little "Edit" button it makes editing way easier.
> fix typo in example-intro.md

- docs/dom-testing-library/api-async.md
To match the recent change to its return type (and TS typedef)
Original issue: dom-testing-library issue [#610](https://github.com/testing-library/dom-testing-library/issues/610)
A note for reviewers, it looks like the linting hooks have made some extra changes here, I'll throw a comment to highlight my intended (much smaller!) change
> Update waitForElementToBeRemoved docs

- docs/react-testing-library/example-intro.md
Assert section in Example page of React Testing Library does not
contains assertion code but SUT. So rename the section to
'System Under Test' and insert a new section that describes assertion
code correctly.
> Correct Assert section in Example page of React Testing Library

- docs/dom-testing-library/api-queries.md
It seems like #386 hasn't been fixed yet, so I added some information about `queryFallbacks` based on the `dom-testing-library` type and documentation text suggested in the issue. Feel free to suggest better wording/organization.
**Preview:** Scroll to the bottom of this section https://deploy-preview-518--testing-library.netlify.app/docs/dom-testing-library/api-queries#byrole
> Add documentation for queryFallback

- docs/dom-testing-library/api-queries.md
This is an alternative to https://github.com/testing-library/dom-testing-library/issues/448 and https://github.com/testing-library/dom-testing-library/pull/675. Rather than changing `dom-testing-library`'s functionality to handle role hierarchies, this keeps back compatibility and warns the user that role matching is literal (without ARIA role inheritance).
[Direct link](https://deploy-preview-520--testing-library.netlify.app/docs/dom-testing-library/api-queries#byrole)
> Warn about literal role matching

- docs/angular-testing-library/examples.md
The angular example repo was recently migrated to Nx, which broke the link from this repo to those examples
> docs(angular): update link to Angular examples

- docs/dom-testing-library/api-queries.md
Adding the docs for [testing-library/dom-testing-library#692](https://github.com/testing-library/dom-testing-library/pull/692)
> docs(ByRole): Add `{ checked: boolean }` option

- docs/dom-testing-library/install.md
Added ecosystem links from Sidebar
> docs: Add ecosystem links from Sidebar

- docs/dom-testing-library/api-queries.md
This came up at my work today.
An engineer thought that a `for` attr on a `<label>` along with a related `<section>` `id` can be queried by `findByLabelText`. 
But really, this is not semantically correct and we end up with this error: 
```
Timed out retrying: Found a label with the text of: Photos, however no form control was found associated to that label. Make sure you're using the "for" attribute or "aria-labelledby" attribute correctly.
```
I think making that explicit in the docs would avoid future confusion.
> [findByLabelText] Adds a bad example using for w/ a non-form element

- docs/using-fake-timers.md
- website/sidebars.json
Following the conversation in https://github.com/testing-library/react-testing-library/pull/743#discussion_r454001823 with @kentcdodds and @eps1lon, 
I've created this page to explain the work with fake timers in testing-library.
I wasn't 100% sure where to put this section so for now I put it under the `Getting Started` section since this is relevant knowledge for all testing library frameworks (I really think we should build a `General` section).
This PR closes #523
> docs(fakeTimers): Explain how to use fake timers in testing-library

- docs/svelte-testing-library/setup.md
Typescript isn't supported by current documentation. With a simple step, we can enable Typescript support.
https://testing-library.com/docs/svelte-testing-library/setup
> Add typescript section to svelte docs to clarify usage with Typescript

- docs/example-reach-router.md
I just add an example of how to test route components with parameters with `@reach/router`.
Previously I had problems testing this type of component, there are very few examples demonstrating this with `@reach/router`, so I decided to publish this example. 🙂
> docs(example-reach-router): add example of route with parameters

- docs/svelte-testing-library/setup.md
I currently have [this PR open](https://github.com/mihar-22/svelte-jester/pull/10) in `svelte-jester` to make it a bit clearer how to get svelte-testing-library to play nice with TypeScript.
Assuming that that gets merged (or something like it), I thought it would be good to add a reference to TypeScript here in the testing-library docs, just so the breadcrumbs are a little easier to follow for a newbie setting up svelte-testing-library who is also using TypeScript. That's what this PR does 🙂
> docs(svelte): add reference to typescript

- docs/dom-testing-library/api-queries.md
See https://github.com/testing-library/dom-testing-library/pull/729
> docs(ByRole): Add `{ pressed: boolean }` option for querying by aria-pressed state

- docs/pptr-testing-library/intro.md
Example is importing `wait` but calling `waitFor`
> Fix use of wait in docs

- docs/dom-testing-library/api-configuration.md
According to the release notes for `dom-testing-library@7` (https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0), this is configurable at the global level.
I also wanted to fix the docusaurus code tabs because they don't seem to register new lines (which is confusing), but... that seems to also be a problem in the docusaurus documentation itself: https://docusaurus.io/docs/en/doc-markdown#language-specific-code-tabs Don't know if anyone has any ideas on that.
> Add `timeout` to configuration docs

- docs/dom-testing-library/api-configuration.md
Documentation for https://github.com/testing-library/dom-testing-library/pull/736
> Document `computedStyleSupportsPseudoElements` config

- docs/dom-testing-library/api-configuration.md
- docs/dom-testing-library/api-events.md
- docs/dom-testing-library/api-queries.md
- docs/svelte-testing-library/setup.md
I noticed there was a small typo (imo) when I was reading  "...will not work in the case where a `for` attr on a label matches and `id` field on a non-form element." and made some changes. 
I've highlighted the text changes in comments as unfortunately the diffs from the changes I made to the "Note" blocks make them hard to immediately spot.
I also took this opportunity to make the "Note" blocks within the page to be consistent with each other. 
The format was based off of this commit I found previously: https://github.com/testing-library/testing-library-docs/commit/5bab9829e25b8c962ffa2ca006b4893c4421762a
i.e. 
Please let me know if I've missed anything! I also ran `format-docs` just to make sure my changes stayed formatted properly - so there were also a few extra `md` files that were …
> docs: fix `api-queries.md` minor grammar typos and "Note" block styles

- docs/dom-testing-library/api-configuration.md
Use the actual name for timeout configuration parameter.
> Rename `timeout` to `asyncUtilTimeout`

- docs/ecosystem-jasmine-dom.md
- docs/ecosystem-jest-dom.md
- website/sidebars.json
There is a minor fix on jest-dom's docs, where instead of suggesting the use of toBeEmpty (deprecated in favor of toBeEmptyDOMElement) I changed it to promote the use of toBeEmptyDOMElement.
Other than that, I added a similar docs page for jasmine-dom 🙂
> Jasmine dom docs

- docs/intro.md
This PR is regarding #574 issue.
This will help newbies developers to understand the purpose of the library and what is not expected out of it.
This will help developers to understand guiding principles better.
> docs: Add 'What this library can't test' section

- docs/dom-testing-library/api-queries.md
Adds documentation for the `level` option on the `ByRole` query introduced in https://github.com/testing-library/dom-testing-library/pull/757
```js
getByRole('heading', { level: number })
```
> Add docs for ByRole 'level' option

- docs/ecosystem-jest-dom.md
- docs/ecosystem-user-event.md
This PR makes the docs for user-event and jest-dom library agnostic because these can be used within multiple Testing Libraries.
> docs: Ecosystem library agnostic

- docs/dom-testing-library/api-configuration.md
`getElementError` was duplicated.
> Documentation: Fix typo and remove duplicate

- docs/preact-testing-library/learn.md
- docs/react-testing-library/migrate-from-enzyme.md
- website/sidebars.json
Hello everyone!
As discussed earlier on #563, we realized a new page for those developers who have experience with Enzyme is needed, for at least the following purposes:
- Why use React Testing Library instead of Enzyme?
- How to use it? (installation, basic usage)
- some helpful link, and explanation to help them get started with the RTL's queries
I did not go into detail on the queries, since it has a complete documentation page itself, and it would be hard to keep two pages updated (I mean if going into detail on this page) instead I just explained the difference and some helpful link to help them get started with the RTL.
Please note that I'm not a native English speaker, so, grammar problem is expected even though I tried to check it with some grammar checker software.
Thanks a lot …
> Add Migrate from Enzyme page

- docs/cypress-testing-library/intro.md
Remove dead cypress testing library example link (file no longer exists)
> remove dead link in examples for cypress testing library documentation

- docs/react-testing-library/migrate-from-enzyme.md
- website/sidebars.json
In [this comment](https://github.com/testing-library/testing-library-docs/pull/568#issuecomment-689109044), @MatanBobi  said the issue with the "Migrate from Enzyme" page which is not showing in the sidebar would be resolved if we change its name in the sidebar (to be equal to the `id` which is defined in the `migrate-from-enzyme.md` )
> Fix migrate from enzyme link in the sidebar

- docs/react-testing-library/api.md
I changed the default value for `baseElement` in render options to be consistent with
- The default value of render result's `baseElement` (it's documented a little further down the page)
- What I'm seeing in my usage of RTL 11.0.2
> Fix baseElement's default value in react docs

- netlify.toml
As @eps1lon suggested in https://github.com/testing-library/dom-testing-library/pull/764.
At the moment when there's no document defined and we're trying to use `screen` there's an error message with a broken link.
This change is to add a redirect to the correct place if a user tries to enter the broken link.
> fix(redirects): redirect error message url to correct page

- docs/ecosystem-query-extensions.md
- website/sidebars.json
Here's a proposal for some documentation that links out to [query-extensions](https://github.com/tjefferson08/query-extensions)
I kept it short and sweet, but I brought over the motivating example from the repo README.md for maximum hype-building 🎉
> docs: add docs page for query-extensions companion lib

- docs/vue-testing-library/cheatsheet.md
Tiny pull request to fix a broken link to the API page `update` section in the Vue cheatsheet.
All the best!
> docs: Fix update event link in Vue cheatsheet

- docs/svelte-testing-library/setup.md
Adds a missing jest transform config setting when using es6 modules.
> docs(svelte): Adds setup information for testing-library-svelte

- docs/cypress-testing-library/intro.md
Adapt instructions on how to add typings (typings are now directly managed in the npm package, instead of via DefinitelyTyped)
> Fix TypeScript tsconfig.json instructions

- docs/react-testing-library/cheatsheet.md
this PR makes `render`'s example in https://testing-library.com/docs/react-testing-library/cheatsheet correct by using `findAllByText` to wait for multiple elements.
> docs: fix cheatsheet example

- docs/dom-testing-library/api-queries.md
for a non input html because the javascript example does not use it.
Closes #236
> removed the example for getting by label

- docs/example-react-redux.md
- netlify.toml
I fixed some issues with the Netlify config in #598 and related merges.
> Netlify config fixes... fixes

- docs/dom-testing-library/cheatsheet.md
- docs/react-testing-library/cheatsheet.md
Remove  replace `wait` for `waitFor` and deprecated methods
> Documentation: Update async section of cheatsheet

- docs/dom-testing-library/api-events.md
- docs/ecosystem-user-event.md
- docs/example-findByText.md
- docs/example-update-props.md
- docs/guide-disappearance.md
- docs/react-testing-library/cheatsheet.md
- website/README.md
- website/sidebars.json
I'm opening a PR for issue #381 to add a simple JS login
form as an example of how to use the `findByText` query 
to find DOM elements that may not be visible immediately. 
I'm open to any feedback as I haven't written tests for 
vanilla JS in a long time (too spoiled with React). ~~Specifically, I
think I need some clarification on an issue I ran into with my example tests
not passing on Codesandbox. Here is the [link](https://codesandbox.io/s/suspicious-jepsen-qlqhi?file=/src/findBy.test.js) to the sandbox,
it's interesting that the first set of tests pass when 
I change the display value from `display: none` to `display: inline`,
but the same doesn't happen with the mock error message `span` 
elements 🤔.~~
~~Here's a screenshot of a type error I ran into with regards to using …
> docs: add findByText example

- docs/dom-testing-library/api-async.md
@kentcdodds I noticed you've just updated the `api-async` docs with documentation on Promise support with `waitFor` but there was a typo introduced 😅  - this PR fixes that typo!
> docs: fix typo in api async docs

- docs/ecosystem-user-event.md
Hey @kentcdodds as explained in [this comment](https://github.com/testing-library/user-event/issues/423#issuecomment-669368863) simulating this in the DOM would be quite tricky, so this PR is to add a `Known limitations` section to the `user-event` referencing the issue.
> docs(user-event): add known limitations section

- src/pages/help.js
Fixes #664 
Might have been caused by a Docosaurus update?
> fix: missing repository url in help page

- docs/dom-testing-library/setup.mdx
- docs/react-testing-library/setup.mdx
We mention some polyfills that don't seem to be necessary any more and could cause confusion when setting up libraries.
- `core-js`: modern Node versions should already support most useful ES features, and common setups like CRA already polyfill anything that isn't supported
- `regenerator-runtime`: this hasn't been needed since Node 6 which has lost support years ago
- `babel-polyfill` and `@babel/polyfill`: deprecated
- Babel 6 module fix for Jest: could still be an issue for older projects that haven't upgraded to Babel 7 yet
- pre-Node 13 `full-icu`: some LTS releases of Node are older than 13 so this is still important to support
> docs: remove notes about some polyfills

- docs/vue-testing-library/api.mdx
Adding this in the hopes of clarifying why VTL uses async fireEvent without overwhelming the user with unnecessary details.
> Explain Why VTL Uses async fireEvent Functions

- docs/ecosystem-testing-library-selector.md
- sidebars.js
Hi! Thanks for a great testing lib. Wrote a small lib for reusable selectors https://github.com/domasx2/testing-library-selector
> docs: add testing-library-selector to ecosystem

- docs/dom-testing-library/api-events.mdx
While it was specified that the date value should follow the ISO 8601 format, this change makes it much clearer for the reader to instantly tell what the ISO 8601 format is without opening another tab to check, just like I did while reading the doc. By using "24" instead of "12", it makes it clear that that portion of the format is referring to the day and not month since there's no 24th month in a calendar year
> Make date format clearer to understand

- docusaurus.config.js
- src/pages/index.js
We have many users on the home page, some of which are lesser known. To keep things simple and fair, I used the [Forbes 500](https://fortune.com/fortune500/) to limit which companies are displayed on the home page. All companies will still be visible on the users page.
> Only show users from the Fortune 500 on the home page

- docs/dom-testing-library/example-intro.mdx
- docs/react-native-testing-library/example-intro.mdx
Maybe Ada isn't just famous for beeing a woman than being the first Programmer :)
Thank you for this nice human-like testing library.
Kudos
> Refer to Ada Lovelace as a programmer

- docs/dom-testing-library/api-queries.mdx
Documentation for the changes proposed in https://github.com/testing-library/dom-testing-library/pull/821.
> docs: expanded filter documentation and examples

- docs/dom-testing-library/api-queries.mdx
Just updating a sentence to make more sense.
From:
- _This throws_ if more than one match is found (use `queryAllBy` instead).
To: 
- _This throws an error_ if more than one match is found (use `queryAllBy` instead).
> docs: Explicitly mention what is thrown

- docs/vue-testing-library/api.mdx
I'm currently learning vue-testing-library and had some trouble trying to set up `vuex` instance with [`simple-vuex`](https://github.com/sascha245/vuex-simple). I found out elsewhere that a possible way to do this would be to use the callback parameter to return a store like the below 
```tsx
const store = createVuexStore(new RootStore())
// doesn't work because `createVuexStore(new RootStore())` is already an instance of `Vuex.Store`
render(MyComponent, {props: {happy: true}, store})
render(MyComponent, {props: {happy: true}}, () => ({ store }))
```
I think I could have noticed this sooner if the documentation described this line in the code: https://github.com/testing-library/vue-testing-library/blob/2312e180b12df3c599e8aa8a0ee85dcff7b108e7/src/vue-testing-library.js#L52. This is what i …
> vue: Clarify what the return value of the callback param does in `render`

- docs/dom-testing-library/api-queries.mdx
- docs/react-testing-library/migrate-from-enzyme.mdx
- docs/vue-testing-library/api.mdx
An attempt at addressing: https://github.com/testing-library/dom-testing-library/issues/700
I'm not sure if my explanation is the best, so feel free to change it or submit other suggestions 🙂
> Add note about global DOM requirement for `screen`

- docs/react-testing-library/setup.mdx
> Use tsconfig/jsconfig paths instead of NODE_PATH

- docs/cypress-testing-library/intro.mdx
The link should be updated since the types [moved](https://github.com/testing-library/cypress-testing-library/pull/148) from DefinitelyTyped into the repo.
> docs: fix the cypress-testing-library types link

- docs/dom-testing-library/api-queries.mdx
Updating this based on thread in [cypress-testing-library issue #146](https://github.com/testing-library/cypress-testing-library/issues/146#issuecomment-753345339)
&ast;By&ast; throws an error when there are more than one element, it is not immediately clear when reading [documentation](https://testing-library.com/docs/dom-testing-library/api-queries#getby) at a glance.
> docs: Update `getBy*` description

- docs/guide-disappearance.mdx
updated `toHaveLength` example to avoid confusion:
The existing example asserts that two elements exist, and this can be a little confusing since the section is named "Asserting elements are not present"
> updated `toHaveLength` example

- docs/queries/bytext.mdx
Hello, I found a broken link while consulting the docs.
I made the patch through the github interface to try it out and haven't yet ran the actual site to make sure it's correct (will do later). I haven't seen any issue related to this one either, if you need one I can create it.
Cheers
> fix: Broken link to getByLabelText

- docs/dom-testing-library/api-accessibility.mdx
- docs/dom-testing-library/api-debugging.mdx
Add periods at end of sentences in _Advanced > Accessibility_ and _Advanced > Debugging_ sections.
> docs: add periods at end of sentences

- docs/example-formik.md
Fixing a typo within the example-formik[ markdown](https://testing-library.com/docs/example-react-formik/).
`submiting` -> `submitting`
`jhon` -> `john`
> Fix typo in example-formik.md

- docs/react-testing-library/setup.mdx
This is the first iteration of the hypothesis of a new tab for `tsx` code on the examples.
https://github.com/testing-library/testing-library-docs/issues/696
> Adding first iteration over TSX on new tab

- docs/queries/byplaceholdertext.mdx
This PR fixes a typo in page title for https://testing-library.com/docs/queries/byplaceholdertext
> Fix typo in title of byplaceholdertext

- docs/angular-testing-library/api.mdx
This PR removes the methods that were removed in the last version of ATL.
Closes https://github.com/testing-library/angular-testing-library/issues/182
> docs: update angular api

- docs/react-testing-library/setup.mdx
When trying to use `jsdom-global` with React tests, you will see these warnings in the console:
```
This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
```
This package does not expose these functions. However, there is a modern fork, `global-jsdom` which offers the same API, but also exports all global DOM APIs properly.
I propose changing the mention to the new package, as it is a more future-proof option.
cc @modosc who is maintaining global-jsdom
> Replace jsdom-global with global-jsdom

- docs/queries/bytext.mdx
Fix a broken link on this page : https://testing-library.com/docs/queries/bytext/
When clicking on the following it's redirecting  to a 404.
----
> docs: Fix broken link

- docs/vue-testing-library/api.mdx
**Updates to Vue Testing Library API page.**
Moved `container` and `baseElement` option docs to the proper section of the page and add docs for those vars in the `render` result section.
Inspiration taken from https://testing-library.com/docs/react-testing-library/api/#render-options
Additional context: https://github.com/testing-library/vue-testing-library/pull/206#discussion_r578240043
> docs(vue): improve container and baseElement docs on VTL api page

- docs/dom-testing-library/api-custom-queries.mdx
Now the custom queries page look like this and has the same title repeated at the top of the page, and it can be removed since it's not necessary
> Remove duplicate "Custom Queries" title

- docs/queries/about.mdx
Fixing issue [793](https://github.com/testing-library/testing-library-docs/issues/793)
> Fix within link

- docs/angular-testing-library/examples.mdx
The url of the example-app has changed due to changes in the structure of the example-app. Code is moved to the `example-app/src` folder
@see https://github.com/testing-library/angular-testing-library/pull/199
> docs(testing-library-angular): Adjust url of the github example-app

- docs/vue-testing-library/cheatsheet.mdx
Changed because when I was following this docs, I got a deprecation warning that I should use waitFor instead of wait.
> Change wait to waitFor in cheatsheet

- docs/react-testing-library/setup.mdx
For #800
Just adding a missing type `RenderOptions` in [Setup/Custom Render](https://testing-library.com/docs/react-testing-library/setup#custom-render) for TypeScript example.
- Modify `docs/react-testing-library/setup.mdx` TypeScript example adding `RenderOptions` type from `@testing-library/react`
> docs: Add missing RenderOptions import

- docs/dom-testing-library/api-custom-queries.mdx
Doc page:
https://testing-library.com/docs/dom-testing-library/api-custom-queries
`getBy*` queries should throw an error after finding more than 1 element!
> docs: Fix custom queries example

- docs/queries/about.mdx
Doc page:
https://testing-library.com/docs/queries/about/#types-of-queries
`queryBy*` returns the only match of an element, not the first one. In that case, it'll throw an Error.
> docs: Correct queryBy* definition

- docs/react-testing-library/faq.mdx
oc page: (q6)
https://testing-library.com/docs/react-testing-library/faq
Replace `wait` which is deprecated with `waitFor`.
> docs: Replace deprecated api

- docs/dom-testing-library/faq.mdx
Doc page: (q4)
https://testing-library.com/docs/dom-testing-library/faq
The suggested plugin is no longer maintained.
Just changed it with [newer/active one](https://www.npmjs.com/package/babel-plugin-jsx-remove-data-test-id).
+Fix a syntax error in q5.
> docs: Fix container destructuring

- docs/react-testing-library/cheatsheet.mdx
The printable cheatsheet link on [this page](https://testing-library.com/docs/react-testing-library/cheatsheet) seems to be broken since gitlab renamed `master` branch to `main`
> Docs: Fix react testing library printable cheatsheet link

- package-lock.json
- package.json
resolves https://github.com/testing-library/testing-library-docs/issues/819
> chore: added missing package

- docs/queries/about.mdx
Assuming by `users` we meant the end-user that will be using the software where testing is implemented and `method` here refers to JS method/function, I have updated two sentences.
Other Minor changes:
1. Capitalize **Queries**.
2. Full stop at the end of a sentence.
3. Changed 1(numeric) to one(text) to stay consistent.
4. Code-highlighted `div` and `span` as in the next point other HTML elements like `img`, `input`, etc were also highlighted.
> docs: minor typos

- docs/ecosystem-user-event.mdx
I was looking around the `user-event` documentation for testing the behaviour of a select component I am building in my app.
I found that the example provided could be more accesible and better aligned with the guidelines and principles of the testing-library. IMHO these kind of examples can make newcomers to have an easier journey learning the library and its core principles.
This is my first contribution to the project so apologies in advance if I am making any mistake. 😃
> docs: modify selectoption example to be more accesible

- docs/dom-testing-library/api-events.mdx
Closes https://github.com/testing-library/dom-testing-library/issues/842
> chore(docs): Update api-events.mdx issue #842

- docs/ecosystem-user-event.mdx
If I correclty understand `screen.getByRole()` method signature, we shouldn't pass here two string arguments.
And, according to [WAI-ARIA spec](https://w3c.github.io/html-aria/), there is no `email` role.
> docs(user-event): Remove strange argument passing

- docs/dom-testing-library/api-events.mdx
These should not be observable in a browser. Since we're all about testing how a user interacts, we should not document these esoteric usages.
Closes https://github.com/testing-library/testing-library-docs/issues/469
> docs: Remove example of synthetic right clicks

- docs/angular-testing-library/api.mdx
The description for `dependencies` actually described `providers`, and there was no `providers` section. Created the `providers` section and updated the `providers`, `componentProviders`, and `dependencies` descriptions.
> docs(angular): fix API

- docs/vue-testing-library/intro.mdx
Otherwise, users get a warning when installing `jest-dom`
> Update docs to suggest @testing-library/jest-dom

- docs/react-testing-library/setup.mdx
Just importing missing ReactElement type on the following page:
https://testing-library.com/docs/react-testing-library/setup
> fix: importing missing ReactElement type

- docs/react-testing-library/example-intro.mdx
The examples in the docs currently use `.toHaveAttribute('disabled')`. However, jest-dom provides `toBeDisabled()`, which does the same thing but is more expressive and gives a better failure message.
> Update docs to use toBeDisabled()

- netlify.toml
Following [this comment](https://github.com/testing-library/testing-library-docs/pull/848#issuecomment-841616705) by @eps1lon, I went over all the redirects and found this one to be redirecting to the wrong place.
> chore: fix a wrong redirect

- docs/ecosystem-user-event.mdx
While I was reading the docs I picked up something that can be better explained :)
> docs: user event english grammar fixes

- docs/dom-testing-library/cheatsheet.mdx
The [Async section](https://testing-library.com/docs/dom-testing-library/cheatsheet#async) on the DOM cheatsheet page has a small formatting issue which causes the `findBy` and `findAllBy` queries to be listed as deprecated APIs. (I got a mini heart attack there to be honest)
---
This PR formats that line a bit, so that it is part of the `waitForElement` paragraph. Here is the result:
> docs: format the deprecation section in DOM cheatsheet

- docs/marko-testing-library/api.mdx
- docs/marko-testing-library/intro.mdx
- docs/marko-testing-library/setup.mdx
This contains a few modernizations to the Marko testing library docs.
Specifically it references the `screen` api which is now fully supported there.
It also mentions the additional `renderResult.cleanup` api.
it adds a note about component render timing and awaiting the `fireEvent` api.
Finally it updates the jest section with the latest examples.
> docs: update marko examples with new apis

- docs/queries/about.mdx
Closes #863
Changes are on line 88 and 90. Others are formatting done at commit time by pre-commit hooks
> About Queries:: Replace the word 'Throw' with 'Throw error'

- docs/webdriverio-testing-library/intro.mdx
WebdriverIO Testing Library assumes that users include the DOM types in
their typescript default types. Add a note to the Typescript section of
the WTL docs to help users who are finding type errors when they haven't.
Related issue: https://github.com/testing-library/webdriverio-testing-library/issues/22
> docs: add note about including dom types in WTL

- docs/dom-testing-library/api-async.mdx
- docs/dom-testing-library/api-debugging.mdx
Documentation for https://github.com/testing-library/dom-testing-library/pull/979
> docs(dom): Document breaking changes of v8

- docs/vue-testing-library/api.mdx
This PR is updates the Vue Testing Library docs for the change made with this PR: https://github.com/testing-library/vue-testing-library/pull/232
> docs(vue): update docs for instantiated store

- docs/vue-testing-library/api.mdx
- docs/vue-testing-library/faq.mdx
This documentation update corresponds to https://github.com/testing-library/vue-testing-library/pull/239 and https://github.com/testing-library/vue-testing-library/issues/210.
> docs(vue): update docs/faq for instantiated router

- docs/vue-testing-library/intro.mdx
> docs(vue): Fix link not found

- docs/ecosystem-eslint-plugin-testing-library.mdx
The ESLint plugin has moved to https://github.com/testing-library/eslint-plugin-testing-library
> docs(ecosystem/eslint): update link for the ESLint plugin

- docs/vue-testing-library/faq.mdx
This update is in response to a conversation between @maxarndt and I [here](https://github.com/testing-library/vue-testing-library/issues/210#issuecomment-871208563). The workaround of resetting `window.location` has some pitfalls, so this PR updates the documentation to only recommend using `abstract` mode.
> docs(vue): update faq for Vue Router abstract mode

- docs/ecosystem-user-event.mdx
Closes #845.
_The content was simply copied from the [user-event keyboard readme](https://github.com/testing-library/user-event/blob/master/README.md#keyboardtext-options), but let me know if changes are needed._
> Add .keyboard method to user-event page

- docs/ecosystem-user-event.mdx
User Event peer depends on DOM Testing Library, so it needs to be manually installed, as stated in the readme.
> Add peer dependency to User Event docs

- docs/react-testing-library/api.mdx
Just a quick fix for URL pointing to `screen.debug` documentation.
> docs: typo fix

- docs/queries/about.mdx
It's very easy to miss the summary table - which is like the most useful part of the page. Have it open by default.
> Make summary table details open by default.

- docs/react-testing-library/api.mdx
Fixed 'libary' to 'library' in: import * as tableQueries from 'my...
> docs: fix typo in example import

- docs/cypress-testing-library/intro.mdx
It seems that chained `.findByText()` API was used incorrectly incorrectly. Running the example on the Cypress page with the HTML below results in this error:
These changes allow the test to succeed.
I specifically ran into this because I tried copy/pasting this example and altering it for my site and I was confused as to why it wasn't working.
___
Example HTML
```html
<!DOCTYPE html>
<html>
<body>
<button>Jackie Chan</button>
<form>
<label for="input">Label text</label>
<input type="text" id="input">
<button type="button">Button Text</button>
</form>
<dialog open>
<p>Do you want to read the docs?</p>
<button>Confirm</button>
</dialog>
</body>
</html>
```
> Fixes findByText usage in Cypress example test

- docs/dom-testing-library/example-intro.mdx
- docs/ecosystem-user-event.mdx
- docs/example-reach-router.mdx
- docs/example-react-context.mdx
- docs/example-react-intl.mdx
- docs/example-react-router.mdx
- docs/guide-disappearance.mdx
- docs/preact-testing-library/example.mdx
- docs/react-testing-library/api.mdx
- docs/react-testing-library/example-intro.mdx
- docs/svelte-testing-library/api.mdx
- docs/svelte-testing-library/example.mdx
https://github.com/testing-library/jest-dom/issues/123#issuecomment-689689656
> docs: fix import issues with jest-dom

- docs/react-testing-library/setup.mdx
The docs currently say that auto cleanup is run automatically if `afterEach` global is present. That is true, however, that doesn't work in Mocha's watch mode, as it executes only the changed files. Globals are not re-run in watch mode. Figuring this out took me an hour or two, so I'm proposing to add info about it to the docs, as I believe it can be helpful for others.
Also, I'm thinking I could add a mocha-specific hook to testing-library/react, similarly to `@testing-library/react/dont-cleanup-after-each`, but that might not be desired, so I think this change to the docs should probably be good enough for now.
> Add note about Mocha's watch mode

- docs/queries/byrole.mdx
This PR adds documentation for feature added at: https://github.com/testing-library/dom-testing-library/pull/943
The feature added according to:
https://github.com/testing-library/dom-testing-library/issues/864
> feat(byRole): add documentation for new option (aria-current) of ByRole queries

- docs/vue-testing-library/faq.mdx
- docs/vue-testing-library/intro.mdx
* updated the links to use this [this list](https://testing-library.com/docs/vue-testing-library/cheatsheet#queries) instead
> docs: fix links to query list for Vue

- docs/react-testing-library/migrate-from-enzyme.mdx
(dom-testing-library/api-queries.mdx) was leading to a 404 page so I did some research on where it should lead. (dom-testing-library/api) had the (queries/about) under Queries and based on the context of the current sentence, I believe (queries/about) is the page where it should lead.
> docs: Update missing link about queries

- docs/learning.mdx
I found that some URL already moved and not found.
Closes https://github.com/testing-library/testing-library-docs/issues/923
> docs: remove invalid URL

- docs/react-testing-library/setup.mdx
[Jest 27 has been released](https://jestjs.io/blog/2021/05/25/jest-27#feature-updates), which no longer defaults to `jest-environment-jsdom`.
> Update incorrect statement about jsdom in Jest

- .github/FUNDING.yml
We're no longer using Open Collective, so I don't think it makes sense for us to keep the link around.
I'm also planning to focus more time on the docs soon, if so I may PR my own sponsor profile link if others are okay with it (of course we can also add links for other maintainers).
> docs: remove Open Collective link

- docs/queries/about.mdx
- docs/queries/byalttext.mdx
Docs for https://github.com/testing-library/dom-testing-library/pull/1049
> docs(ByAltText): Add notes about support for custom elements

- docusaurus.config.js
Since there's no migration guide for docusaurus v2 yet, I read the [v1 migration guide](https://v1.docusaurus.io/blog/2021/11/05/algolia-migration) and updated according to it and according to [algolia's recommendations](https://docsearch.algolia.com/docs/migrating-from-legacy/).
I tested this one locally and search seems to work properly.
Resolves https://github.com/testing-library/testing-library-docs/issues/965
> chore: update algolia credentials

- docs/angular-testing-library/api.mdx
Similar to https://github.com/testing-library/testing-library-docs/pull/745
> fix: broken queries link in angular api

- docs/vue-testing-library/examples.mdx
Examples of vue-testing-library had links pointing to `master` branch but the branch is renamed to `main` now. Though GitHub redirects to the renamed branch, it'd be good to have this updated and save a redirect :)
> Update vue-testing-library examples' links to point to `main` branch

- docs/svelte-testing-library/api.mdx
Fixes the link to the Svelte component's _Client-Side Component API_ documentation.
To be: https://svelte.dev/docs#run-time-client-side-component-api-creating-a-component
> fix: svelte client-side component api link

- docs/ecosystem-user-event.mdx
- docs/user-event/api-clipboard.mdx
- docs/user-event/api-convenience.mdx
- docs/user-event/api-keyboard.mdx
- docs/user-event/api-pointer.mdx
- docs/user-event/api-utility.mdx
- docs/user-event/install.mdx
- docs/user-event/intro.mdx
- docs/user-event/options.mdx
- docs/user-event/setup.mdx
- sidebars.js
Add documentation for `user-event@14` alongside `v13` for rest of `beta`.
New projects / projects that someone is actively working on should probably already switch to `v14-0.0-beta`, but I want to wait for more feedback before declaring this `stable`.
I hope the new documentation helps with this.
> feat: document user-event v14

- netlify.toml
Add a top-level redirect for sharing an URL that is a) shorter and b) independent from possible future reorganizing of docs pages.
> feat: add top-level redirect for `user-event`

- docs/react-testing-library/setup.mdx
Jest test files without using relative imports in CRA in now allowed with the ability to configure [absolute imports](https://create-react-app.dev/docs/importing-a-component/#absolute-imports). Removing note section.
> Update relative imports CRA note

- docs/vue-testing-library/intro.mdx
If you don't install using @next and you are using Vue3 you get an error regarding vue-template-compiler not being found.
> Add vue3 quickstart instruction

- docs/queries/byrole.mdx
Use `img` instead of `image` since `image` is not a valid aria-role. 
> For example `<img aria-label="fancy image" src="fancy.jpg" />` will be returned for both `getByAltText('fancy image') and getByRole('image', { name: 'fancy image' })`.
> fix(queries): use role `img` instead of `image`

- docs/user-event/intro.mdx
It fixes the link in Github. ~I'm not sure if it's gonna fix the [link on the website](https://testing-library.com/docs/user-event/intro/#:~:text=recommend%20to%20use-,userEvent.setup(),-when%20rendering%20your)~
https://deploy-preview-996--testing-library.netlify.app/docs/user-event/setup
> fix(userEvent): setup borken link

- docs/ecosystem-user-event.mdx
User Interactions > user-event v13 > `type(element, text, [options])`:
- Add an example that shows how to prepend text with `type`.
> docs(user-event): add example to prepend text with `type`

- docs/ecosystem-user-event.mdx
Fix code example of [`clear`](https://testing-library.com/docs/ecosystem-user-event#clearelement) API in **user-events v13** docs.
The current code example does not work and causes confusion because React value prop without an onChange handler causes the field to be read-only. Also `value` attribute is `null`.
So I changed two things:
- `value` to `defaultValue` prop 
-  `toHaveAttribute('value', '')` to `toHaveValue('')`
The example code for `clear` in [Utility APIs ](https://testing-library.com/docs/user-event/utility#clear) is also following this method.
> docs(user-event): fix code example of `clear` API

- docs/vue-testing-library/intro.mdx
The `latest` tag of `@testing-library/vue` points to a version that is incompatible with Vue 2. This is not reflected in the documentation so I added the correct versions to the example command.
> Clarify compatible versions for Vue 2 and Vue 3

- docs/preact-testing-library/api.mdx
When I copied the code example, there was an error, so I fixed it.
https://testing-library.com/docs/preact-testing-library/api/#example-1
- Fix syntax error
- Delete undefined prop
- https://developer.mozilla.org/en-US/docs/Web/API/Event/Event
> docs: fix fireEvent Example code

- docs/dom-testing-library/api-events.mdx
- docs/dom-testing-library/install.mdx
- docs/ecosystem-user-event.mdx
- docs/example-findByText.md
- docs/example-formik.md
- docs/example-input-event.mdx
- docs/example-react-router.mdx
- docs/guide-events.mdx
- docs/queries/about.mdx
- docs/react-testing-library/migrate-from-enzyme.mdx
- docs/user-event/api-keyboard.mdx
- docs/user-event/install.mdx
- docs/user-event/intro.mdx
- docs/user-event/options.mdx
Update all references to `user-event` preparing for the upcoming release.
This should be merged once the version is released on `latest`:
> docs: update user-event references

- docs/react-testing-library/api.mdx
[Preview](https://deploy-preview-1034--testing-library.netlify.app/docs/react-testing-library/api#legacyroot)
Docs for https://github.com/testing-library/react-testing-library/pull/1031
> docs: Add `render`#`legacyRoot`

- docs/user-event/intro.mdx
fixes missing curly braces in the intro code example: `screen.getByRole('button', name: /click me!/)`
also formats the mdx
> docs(user-event): fix a typo

- docs/queries/byrole.mdx
Docs for https://github.com/testing-library/dom-testing-library/pull/1120
> docs: queryByRole new description option

- .all-contributorsrc
- docs/angular-testing-library/faq.mdx
- sidebars.js
This adds changes suggested by @timdeschryver at https://github.com/testing-library/angular-testing-library/issues/288#issuecomment-1076475686
> docs(angular): add faq with shallow rendering example

- docs/user-event/options.mdx
Add docs for https://github.com/testing-library/user-event/pull/907
> docs(user-event): add `advanceTimers` option

- docs/user-event/options.mdx
Change docs according to https://github.com/testing-library/user-event/pull/928
> docs(user-event): use `globalThis`

- docs/react-testing-library/api.mdx
Docs for https://github.com/testing-library/react-testing-library/pull/991
> docs: `@testing-library/react#renderHook`

- docs/example-react-router.mdx
Since react-router-dom v6, there's no history object on Router anymore. Instead, the objects navigator and location needs to be used. Reference:
https://stackoverflow.com/questions/69859509/cannot-read-properties-of-undefined-reading-pathname-when-testing-pages-in
> Update Router props based on react-router-dom v6

- netlify.toml
Noticed consistent errors in the Netlify build log about a missing `format-docs` script. Looks like this happened back with #957.
Here is a recent build log: https://app.netlify.com/sites/testing-library/deploys/627228a19893d40008ebd381
> chore: Update netlify config for `format-docs` to `format` script change

- docs/angular-testing-library/examples.mdx
- docs/bs-react-testing-library/examples.mdx
- docs/cypress-testing-library/intro.mdx
- docs/dom-testing-library/api-custom-queries.mdx
- docs/dom-testing-library/example-intro.mdx
- docs/ecosystem-bs-jest-dom.mdx
- docs/ecosystem-jest-native.mdx
- docs/marko-testing-library/setup.mdx
- docs/react-native-testing-library/example-intro.mdx
- docs/react-native-testing-library/setup.mdx
- docs/react-testing-library/api.mdx
- docs/react-testing-library/example-intro.mdx
- docs/react-testing-library/faq.mdx
- docs/react-testing-library/setup.mdx
- docs/svelte-testing-library/setup.mdx
- docs/testcafe-testing-library/intro.mdx
This PR is an attempt to unify the style of file titles in the documentation. I noticed that several code blocks had comments with file titles instead of `title` prop.
Also I made few minor styling changes. Just could not leave these. Hope that’s fine.
> style: add missing file `title` prop to code blocks

- docs/react-testing-library/setup.mdx
Added instruction on jsdom setup as it now isn't shipped with jest as of v28.
https://jestjs.io/docs/upgrading-to-jest28#jsdom
"If you are using JSDOM test environment, jest-environment-jsdom package now must be installed separately"
> Updated jest v27 instructions to v28

- docs/example-react-transition-group.mdx
From https://github.com/testing-library/testing-library-docs/pull/1066#discussion_r877935074
Adding missing `useState` import to React Transition Group example.
> docs: add missing `useState` import to React Transition Group example

- docs/dom-testing-library/setup.mdx
Vitest doesn't need `global-jsdom`, setting `environment` to `jsdom` already defines it globally.
> docs: Vitest doesn't need global-jsdom

- docs/dom-testing-library/api-configuration.mdx
Docs for https://github.com/testing-library/dom-testing-library/pull/1138
> docs: add docs about defaultIgnore config

- docs/user-event/intro.mdx
Several engineers at our company have had trouble understanding what the v14 upgrade entailed for us, after just looking at the intro. Having now actually done it, it's simple enough, but these changes attempt to clarify things in the intro by 
a) improving grammar
b) clarifying a few key points and examples
c) providing a direct link to the v14 changelog
> Improving intro clarity

- docs/angular-testing-library/faq.mdx
It turned out that `ngMocks.guts` isn't the best approach to mock dependencies, especially for standalone components.
The right way is to use `MockBuilder(ThingToTest, ItsModule)` or `MockBuilder(StandaloneComponent)`.
Related PR in `ng-mocks`: https://github.com/ike18t/ng-mocks/pull/2922
> docs: ng-mocks example for standalone components

- docs/react-testing-library/api.mdx
fix: https://github.com/testing-library/testing-library-docs/issues/249
> doc: change use of container.firstChild to asFragment

- docs/example-react-router.mdx
docs(react-router): fixes react router v6 examples, removes outdated comments 
closes #1065
Details
- converted the examples to use "<BrowserRouter>" and "<MemoryRouter>", according to v6 docs (https://reactrouter.com/docs/en/v6/routers/browser-router). 
- moved the manual "history" use to the v5 example only, as it is not recommended in v6.
> docs(react-router): fixes react router v6 examples, removes outdated comments

- src/css/custom.css
Margin of first and last grid item shift top and bottom row layout off-center.
> Fixed grid layout

- docs/user-event/intro.mdx
The current intro makes it sounds like `user-event` can test all valid user interactions, and is a replacement for `fire-event` in all user-interaction cases. However, in our engineering dept., we've found that this is not the case. For example, to pick a specific value on a slider, we use:
```js
fireEvent.change(screen.getByRole('slider'), { target: { value: '3000' } })
```
We haven't been able to find any `user-event` equivalent to this. So unless there's something we're not aware of (and we've [posted the question to SO](https://stackoverflow.com/q/72775505/9154668) and received no responses), then noting that `user-event` can not replace `fire-event` in all cases would improve the clarity and usefulness of the `user-event` intro.
> Clarifying user-event's capabilities vs fire-event

- docs/queries/about.mdx
Added documentation to the modification of logTestingPlaygroundURL (adding return value) - Resolves #1125
> modify logTestingPlaygroundURL documentation

- docs/example-external.mdx
I am in no way affiliated with the project, I just wanted to add a link that was not dead.
> Just add an alternative location for the React Testing Examples

- docs/queries/about.mdx
- docs/svelte-testing-library/api.mdx
- docs/svelte-testing-library/example.mdx
The original Testing Library/Svelte docs have not beed updated in quite a while and I believe the actual examples were written prior to `screen` being released in [DOM Testing Library v6.11.0](https://github.com/testing-library/dom-testing-library/releases/tag/v6.11.0). 
Best practice is to use the `screen` and not access the `container` directly for queries.
> Svelte: Update documentation for current best practices

- docs/svelte-testing-library/setup.mdx
I work extensively in Svelte and I can say without a doubt that using Vitest over Jest is highly preferred since almost all Svelte build tools leverage Vite to build and, Svelte has a high preference for ES6 modules which Jest has a hard time handling.  I thought it would be helpful to update these docs for Svelte users with Vitest instructions since that will most likely be their preferred way of consuming this library. 
Also, let me know if you want me to reorganize things as I can see how people would get confused by the Typescript and preprocessors section which are specific to Jest right after the Vitest instructions. 
Minor Note: Sveltekit has its own setup with https://github.com/nickbreaton/vitest-svelte-kit
Do we want to add a section for this too?
> docs: Update Svelte setup.mdx with Vitest configuration instructions.

- docs/example-react-router.mdx
No Need for exact in Route of v6. it acts as exact by default.
> docs: remove exact prop in v6 Route example

- docs/svelte-testing-library/intro.mdx
- docs/svelte-testing-library/setup.mdx
After my last update I talked with some of the guys on the Svelte discord and its pretty well accepted that Vitest is the preferred unit testing framework for Svelte. Please refer to the comment from @benmccann  at the bottom of this [issue](https://github.com/sveltejs/kit/issues/4423)
So I updated the Setup docs to put Vitest as the preferred. I also added a section for the Sveltekit plugin for people using Sveltekit. 
As for the Jest Section I moved it to the bottom and I set the Typescript and preprocess sections as subsections since those are Jest specific. I was wondering if I should add sections like those to the Vitest section? The svelte-vite-plugin simply just reads your svelte.config.  So if you were already building the project in TS or using preprocessors you don't need to do …
> Update Svelte Setup to reflect current preferred testing framework

- docusaurus.config.js
- package-lock.json
- package.json
Docusaurus is now officialy release to v2 🦖
This PR:
- updates docusaurus
- removes the [removed properties](https://docusaurus.io/docs/2.0.0-rc.1/migration/manual#removed-fields)
> update docusaurus version 2

- docs/queries/about.mdx
Linked firefox extension was removed from the store; update the text to remove its mention
> Remove mention to Firefox extension in about.mdx

- docs/react-native-testing-library/example-intro.mdx
Updated example for clarity & applied recommended practices like using `screen` and `jest-native` matchers.
> docs: update React Native example to use recommended practices.

- docs/angular-testing-library/intro.mdx
- docs/bs-react-testing-library/intro.mdx
- docs/cypress-testing-library/intro.mdx
- docs/dom-testing-library/install.mdx
- docs/dom-testing-library/setup.mdx
- docs/ecosystem-bs-jest-dom.mdx
- docs/ecosystem-jasmine-dom.mdx
- docs/ecosystem-jest-dom.mdx
- docs/ecosystem-jest-native.mdx
- docs/ecosystem-query-extensions.mdx
- docs/ecosystem-react-select-event.mdx
- docs/ecosystem-riot-testing-library.mdx
- docs/ecosystem-rtl-simple-queries.md
- docs/ecosystem-testing-library-selector.md
- docs/marko-testing-library/intro.mdx
- docs/nightwatch-testing-library/intro.mdx
- docs/pptr-testing-library/intro.mdx
- docs/preact-testing-library/intro.mdx
- docs/react-native-testing-library/intro.mdx
- docs/react-testing-library/intro.mdx
- docs/react-testing-library/migrate-from-enzyme.mdx
- docs/react-testing-library/setup.mdx
- docs/svelte-testing-library/intro.mdx
- docs/svelte-testing-library/setup.mdx
- docs/testcafe-testing-library/intro.mdx
- docs/vue-testing-library/intro.mdx
- docs/webdriverio-testing-library/intro.mdx
- docusaurus.config.js
- package-lock.json
- package.json
Hey folks 👋
I've introduced this little plugin to introduce automatic conversion of npm commands to yarn.
> feat: convert npm to yarn commands on docs

- docs/react-testing-library/setup.mdx
> docs: add TypeScript example for custom-queries.js

- docs/angular-testing-library/api.mdx
- docs/angular-testing-library/examples.mdx
This PR add docs for a new Angular feature
> docs(angular): add standalone component example

- docs/vue-testing-library/api.mdx
- docs/vue-testing-library/examples.mdx
Fix for https://github.com/testing-library/vue-testing-library/issues/280
> chore: update vue api doc to match implementation

- .vscode/settings.json
- docs/react-testing-library/example-intro.mdx
As an educator I've heard a lot of students complaining about the lack of a simpler setup example on the documentation.
Something like a 'Hello World' for RTL to get them started before diving into the extensive full example.
I think this quickstart example will help newcomers start with a simple setup, test it out on their project and move on from there to the more advanced concepts and probably to the Full example in this page.
> Add quickstart example

- docs/dom-testing-library/api-debugging.mdx
Update docs for https://github.com/testing-library/dom-testing-library/pull/1166.
NOTE: This is written in the same style as the docs for the other environment variable. I'd be happy to change one or both of those sections to some other format provided I'm given an example of a pattern to follow.
> update docs to describe usage of COLORS env variable

- docs/user-event/setup.mdx
I spent an hour trying to figure out what was wrong with my code, not realizing that user-events was an unnamed export. Please put an import statement somewhere in the docs, if not here, to save poor idiots like myself.
> docs: Update setup to include import statement

- docs/webdriverio-testing-library/intro.mdx
WebdriverIO chainable queries were added to @testing-library/webdriverio in [v3.1.0](https://github.com/testing-library/webdriverio-testing-library/releases/tag/v3.1.0). Add documentation for the new queries along with how to add them to Browser and Element types when using Typescript.
> docs: add wdio testing library chainable queries

- docs/react-testing-library/api.mdx
Error in renderHooks example, must be return the props object instead of a string
> docs: fix api docs rtl

- docs/react-testing-library/setup.mdx
Remove FC type of functional component in react typescript example since its use is discouraged as stated [here](https://github.com/facebook/create-react-app/pull/8177)
> remove FC type of functional component in example

- docs/queries/byrole.mdx
issue: https://github.com/testing-library/testing-library-docs/issues/1190
`*ByAltText` query will not return for `<img aria-label="XXX" src="fancy.jpg" />` ([see sandbox](https://codesandbox.io/s/test-query-priority-mi4inx?file=/src/ByAltTest.test.tsx:329-436)).
> docs: fix incorrect description of getByAltText

- docs/dom-testing-library/api-async.mdx
Coming from #1204
This PR back-ports my feedback on the new web docs that were partly copy-pasted from this page.
> remove 'will' from docs

- docs/queries/about.mdx
Added a note about using `exact` option with *byRole queries to enable fuzzy matching. Please see details of the issue here:
https://github.com/testing-library/dom-testing-library/issues/1157
Users may expect to use `exact: false` for substring matching whereas it doesn't affect the way of filtering out DOM nodes by accessible names.
> Usage of exact option with *byRole queries

- docs/angular-testing-library/api.mdx
> docs: be more specific about current Angular's rerender behavior

- docs/vue-testing-library/setup.mdx
Related to: https://github.com/testing-library/vue-testing-library/issues/296 and https://github.com/testing-library/vue-testing-library/pull/297
> vitest setup to enable cleanup in afterEach

- docs/example-formik.md
Just a suggestion to update all `screen.get` queries to use `ByRole`, where currently 1/4 does.
> Reflect `byRole` best standard

- docs/queries/byrole.mdx
Don't merge before https://github.com/testing-library/dom-testing-library/pull/1211 is released in `latest`
Docs for https://github.com/testing-library/dom-testing-library/pull/1211
> ByRole: Remove MatchOptions

- docs/dom-testing-library/api-configuration.mdx
- docs/queries/byrole.mdx
Adding docs following the [discussion](https://github.com/testing-library/testing-library-docs/pull/1214#discussion_r1099027874) by @eps1lon and @timdeschryver and some minor rephrasing.
> docs: explain suggest in byRole

- docs/example-input-event.mdx
1. 3 instances of `const` were missing from function declarations - these have been added
2. The `getByLabelText` on line 35 was underlined in red saying
to use `screen` instead of `utils`
Resolves #1222
> docs: Fix example input event code errors

- docs/queries/byrole.mdx
The Paciello Group is now called TPGi https://www.tpgi.com/the-paciello-group-is-now-tpgi/ and the previous link is now redirected to the home page of TPGi.
Could not find a PR template, please let me know if there is one around.
> Update link to "What is an accessible name" guide

- docs/vue-testing-library/api.mdx
Teeny tiny cleanup from the overhaul done in #1141.
This callback used to provide a way to install additional plugins, but now that's handled by [the `global.plugins` array from `@vue/test-utils` mount options.](https://test-utils.vuejs.org/api/#global)
> docs(vue): remove extra callbackFunction parameter

- docs/vue-testing-library/examples.mdx
Vue examples aren't using screen although it is the recommended way of querying.
> docs: change vue examples to use screen

- docs/queries/byrole.mdx
Docs for https://github.com/testing-library/dom-testing-library/pull/1222
[Rendered preview](https://deploy-preview-1232--testing-library.netlify.app/docs/queries/byrole#busy)
> feat(ByRole): Allow filter by busy state

- docs/queries/byrole.mdx
Docs for https://github.com/testing-library/dom-testing-library/pull/1223
[Rendered preview](https://deploy-preview-1230--testing-library.netlify.app/docs/queries/byrole#value)
> feat(ByRole): Allow filter by value state

- docs/react-testing-library/example-intro.mdx
This PR updates the example intro for the React section.
It follows the eslint suggestion: "Prefer `findByRole` query over using `waitFor` + `getByRole`".
I believe this fixes #1186.
> Update example-intro.mdx to use findBy instead of waitFor

- docs/queries/bylabeltext.mdx
The sentence talks about selecting a `<label>` but the example is selecting a `<input>`. This PR fixes the sentence.
> fix(byLabelText): wording about the selector

- docs/queries/byrole.mdx
value is not supported in headings
and the example is about role='spinbutton' anyway so it's a mistake.
> fix wrong role

- docs/user-event/intro.mdx
It took me a while to understand how to import `userEvent` and even to understand that it was a separate library. 😶‍🌫️ 
I think adding these imports would make it clearer for users that get into the page and quickly scroll for the code examples.
> Add imports to `user-event` intro documentation

- docs/vue-testing-library/examples.mdx
File was [deleted here](https://github.com/testing-library/vue-testing-library/pull/303/files#diff-f06baa1c59c6f049eebdb2bebe06ae4455a8440ef9b260ac45bec473d2959203).
> docs: update examples to remove a deleted example

- docusaurus.config.js
- Updated docs to add alt text to img to fix critical accessibility issue as seen with axe devTools chrome extension
**Before Change:**
**After Change:**
> docs: added alt text to img to fix a11y issue

- docs/angular-testing-library/api.mdx
based on changes made in https://github.com/testing-library/angular-testing-library/pull/366
> docs(angular): update rerender api

- docs/dom-testing-library/api-debugging.mdx
- docs/queries/about.mdx
move `debug` section from 'About Queries` menu tab to `Debugging` menu tab
Issue #1276
> #1276: update debug doc

- src/pages/index.js
- adding alt attributes to images for accessibility compliance
- tags that are for decorative purposes have an empty alt attribute
> fix(a11y): reducing homepage accessibility issues by 64%

- docs/react-testing-library/setup.mdx
- docs/svelte-testing-library/setup.mdx
- docs/webdriverio-testing-library/intro.mdx
Just a couple of quick capitalization fixes:
- `Javascript` -> `JavaScript`
- `Typescript` -> `TypeScript`
> Fix capitalization

- docs/angular-testing-library/api.mdx
- docs/angular-testing-library/examples.mdx
- docs/angular-testing-library/version-compatibility.mdx
- sidebars.js
Because I received this question a couple of times the last weeks :)
> angular: add Version compatibility table

- docs/user-event/api-convenience.mdx
I wrote the example code for the "user-event/Convenience APIs".
[user-event v13](https://testing-library.com/docs/ecosystem-user-event)  I think it would be helpful for more people to have example code like on the page.
Except for "hover" and "unhover", this is based on the [user-event v13](https://testing-library.com/docs/ecosystem-user-event) example code.
The example code all passes the tests fine.
> docs: userEvent/convenience Example Code

- docs/ecosystem-cli-testing-library.mdx
- sidebars.js
Per a conversation I had with @nickmccurdy, I've added my CLI Testing Library project to the ecosystem section of the website.
This was suggested by @kentcdodds as well on X/Twitter: https://twitter.com/kentcdodds/status/1688782457838112768
Closes #1069
> docs: add CLI Testing Library to ecosystem

- docs/queries/about.mdx
- Change the link text from `Chrome` to `Testing Playground`
- Remove `/related` from the URL
> fix: link text and url of chrome extension

- docs/learning.mdx
I created a site for my angular challenges. There is a page specific for testing purposes and nicer than a readme file.
> fix documentation: fix angular challenge url

- docs/user-event/api-utility.mdx
I refactored `userEvent` to `.setup()` instead of utilizing it directly.
Thank you for checking it out and providing feedback.
> refac: refactoring userEvent utility example code

- src/css/custom.css
- src/pages/help.js
> Docs: Updated UI of Page[Help]

- docs/react-testing-library/api.mdx
https://github.com/testing-library/testing-library-docs/pull/1319
I added the `unmount` part of the `renderHook`, but didn't get around to adding the top link, so I worked on that.
> imp: add unmount top link

- docs/user-event/options.mdx
The delay value gets passed into setTimeout which takes a value in milliseconds (not seconds).
fixes #1335
> Update user event's delay option to say milliseconds instead of seconds

- docs/preact-testing-library/api.mdx
- docs/react-testing-library/api.mdx
- docs/svelte-testing-library/api.mdx
- docs/svelte-testing-library/setup.mdx
- docs/vue-testing-library/api.mdx
@testing-library/svelte requires `globals: true` to run `cleanup()` after each test, but this is [a bit easy to miss in the docs](https://github.com/testing-library/testing-library-docs/issues/1331). This PR highlights this required step.
> Highlights necessary step in Svelte setup

- docs/queries/byrole.mdx
Improves the example of queryByRole({ current });
https://github.com/testing-library/dom-testing-library/pull/1273
> feat: Improving example of query/byrole #current

- netlify.toml
This PR adds a new redirect to RTL template for reproductions
IMO, we can create more templates (DTL, ATL and more).
I can definitely take the DTL if we want.
> docs: add redirect to new rtl template

- netlify.toml
This PR is a followup to https://github.com/testing-library/testing-library-docs/pull/1346 and adds DTL template.
I'll now work on an ATL template.
> docs: add redirect to dtl template

- docs/angular-testing-library/api.mdx
This PR adds documentation for a new API introduced in ATL.
> angular: document deferrable views

- docs/queries/byrole.mdx
Adds notes about performance of *ByRole queries to the Queries > ByRole page.
`getByRole` and the likes are known to be slow at times and documentation has been requested[^1][^2][^3] to help make this more visible.
This has been known for several years[^1] and performance remains a concern[^4] so I believe it is worthwhile adding to the docs. 
I think it's important to have a balance of conveying the importance of `getByRole` while still sharing this information about the performance so users can make an informed decision if performance is a problem.
This relates to issues
- https://github.com/testing-library/dom-testing-library/issues/820
- https://github.com/testing-library/dom-testing-library/issues/698
These issues have great discussion around this topic, which I've attempted to …
> docs: add query ByRole performance notes

- docs/angular-testing-library/api.mdx
Angular is adding some more functionality around testing.
This was recently added in ATL (with https://github.com/testing-library/angular-testing-library/pull/431), this PR updates the documentation to add the new API.
While adding the new API, I also noticed `deferBlockStates` was undocumented.
> angular: add deferBlockBehavior to the docs

- docs/svelte-testing-library/intro.mdx
- docs/svelte-testing-library/setup.mdx
Both the Vitest and Jest setup instructions for svelte-testing-library were a bit out of date. This PR updates them both.
The examples section needs updating, too, but I'll submit that as a separate PR.
- #1331
- testing-library/svelte-testing-library#294
- testing-library/svelte-testing-library#222
- testing-library/svelte-testing-library#252
> docs(svelte-testing-library): update vitest and jest setup instructions

- docs/svelte-testing-library/faq.mdx
Companion PR to testing-library/svelte-testing-library#311 to resolve testing-library/svelte-testing-library#206
- Add FAQ entry for "Why aren't transition events running?"
- Update "How do I test file upload?" with simpler solution based on `user-event`
- Fix syntax issue in "Why isn't `onMount` called when rendering components?" snippet
> docs(svelte-testing-library): add FAQ entry for transition events

- docs/svelte-testing-library/example.mdx
We've got a few tickets over in svelte-testing-library asking for how to test certain things. This PR adds examples for all the open requests:
- Closes testing-library/svelte-testing-library#48 
- Closes testing-library/svelte-testing-library#117 
- Closes testing-library/svelte-testing-library#178
- Closes testing-library/svelte-testing-library#211
- Closes testing-library/svelte-testing-library#296
I've tested these examples and they all seem to be working, but I'm not the world's best speller nor typist, so any help catching typos is very much appreciated!
- Update basic example based on updated setup instructions in #1360 
- Add example for testing events with both `on:xyz` and function props
- Add example for testing slots
- Add example for testing two-way data binding
- Add example …
> docs(svelte-testing-library): add event, slot, binding, context examples

- docs/dom-testing-library/install.mdx
- docs/solid-testing-library/api.mdx
- docs/solid-testing-library/intro.mdx
- netlify.toml
- sidebars.js
Added a Solid Testing Library section!
Note: this is mostly a port of https://github.com/solidjs/solid-testing-library current docs. Please let me know if changes are needed :)
Closes #1364
> docs(solid-testing-library): add solid testing library docs

- docs/react-testing-library/example-intro.mdx
Followup PR for https://github.com/testing-library/testing-library-docs/pull/1327/
This is a cherry pick of @kettanaito's and @timdeschryver's commits with the last fix needed to push this update.
> docs: udpate msw example

- docs/react-testing-library/intro.mdx
For https://github.com/testing-library/react-testing-library/pull/1305
> New install instructions for RTL

- docs/svelte-testing-library/setup.mdx
Also fixes a missing `.` and missing `,` in the example Jest configuration file.
Closes #1388
> docs(svelte-testing-library): add sveltekit setup instructions

- docs/react-testing-library/intro.mdx
Following https://github.com/testing-library/react-testing-library/pull/1319
> docs: recommend installing `@types/react`

- docs/guides-using-fake-timers.mdx
- docs/user-event/options.mdx
fixes https://github.com/testing-library/testing-library-docs/issues/1180
The docs do not clarify how to use fake timers together with `user-event`. Added a section with an example how to properly set it up.
> docs: clarify fake timer usage with user-event

- docs/react-testing-library/setup.mdx
It will be easier for the user if you replace the TabItem values with general ones, because if you select a tab in one of the code examples, TypeScript, then other examples change asynchronously (i.e. the code examples will remain in JavaScript, or vice versa).
> fix: replace the TabItem values with general ones

- README.md
Use the updated link for the all contributors badge, based on this: https://allcontributors.org/docs/en/bot/faq#all-contributors-badge-count-does-not-update
> docs: fix all contributors badge

- docs/react-testing-library/intro.mdx
Docs for https://github.com/testing-library/react-testing-library/pull/1305
Explanation that we need to manually install `@testing-library/dom` as it's moved to peer dependency.
**Do not merge before merging the RTL PR**
> docs: move dtl to peerdeps for rtl

- docs/react-testing-library/api.mdx
- docs/react-testing-library/cheatsheet.mdx
Some links were referencing the old react docs. This PR is updating the links to the equivalent in the new docs.
Also, the `act` was mentioned as coming from `react-dom/test-utils` but since version [18.3.1](https://github.com/facebook/react/releases/tag/v18.3.1) it changed, and now it is imported from `react`.
> docs: update react doc links

- docs/svelte-testing-library/setup.mdx
Companion docs PR to testing-library/svelte-testing-library#375 and svelteness/svelte-jester#283. Svelte 5 introduces the concept of "Svelte modules," which are plain JS and TS files that are run through the Svelte compiler to add support for Svelte 5's "runes" reactivity system.
This is handled well in Vitest by Svelte's first-party `vite-plugin-svelte`, but requires additional setup to work in Jest.
This PR add newly required Svelte 5 setup instructions for Jest and notes that `svelte-jester >= 5` is now required. I'm going to keep this listed as a draft until I've merged and verified testing-library/svelte-testing-library#375 in some real-life projects. That being said, these additional `jest.config.js` changes will not cause any issues with existing Svelte 4 projects
> docs(svelte-testing-library): add Svelte 5 setup instructions for Jest

- docs/angular-testing-library/intro.mdx
- docs/angular-testing-library/version-compatibility.mdx
Prepare docs for ATL v17
Needs to be merged after https://github.com/testing-library/angular-testing-library/pull/460
> docs: update docs for ATL v17

- src/css/custom.css
- Improves accessibility score to 100% for home and doc pages
- used [Deque color contrast tool](https://dequeuniversity.com/rules/axe/4.9/color-contrast?application=AxeChrome) to determine closest accessible color to current color in production
- Closes issue [1405](https://github.com/testing-library/testing-library-docs/issues/1405)
> chore(a11y): improving a11y score to 100% for home and doc pages

- docs/angular-testing-library/api.mdx
Updated documentation based on [this issue regarding documentation inconsistency for deferBlockBehavior](https://github.com/testing-library/testing-library-docs/issues/1403)
> update deferBlockBehavior documentation

- docs/queries/byrole.mdx
I fixed broken the link that was added in https://github.com/testing-library/testing-library-docs/pull/1410 .
And applied formatting using Prettier.
> fix(byrole.mdx): broken link

- docs/angular-testing-library/api.mdx
Update the Angular API:
- mark properties as deprecated
- document new properties
Closes https://github.com/testing-library/angular-testing-library/issues/476
Closes https://github.com/testing-library/angular-testing-library/issues/467
> Update angular api

- docs/angular-testing-library/examples.mdx
Closes https://github.com/testing-library/angular-testing-library/issues/490
> freshen up Angular example

- docs/react-testing-library/faq.mdx
Closes https://github.com/testing-library/testing-library-docs/issues/1060
[Preview](https://deploy-preview-1416--testing-library.netlify.app/docs/react-testing-library/faq) ("How do I test thrown errors in a Component or Hook?")
> Add docs for thrown errors from render

- docs/react-testing-library/api.mdx
- docs/react-testing-library/faq.mdx
Docs for https://github.com/testing-library/react-testing-library/pull/1354
https://deploy-preview-1417--testing-library.netlify.app/docs/react-testing-library/api#oncaughterror
https://deploy-preview-1416--testing-library.netlify.app/docs/react-testing-library/faq/
Testing error boundaries is closely related to `onCaughtError` so it felt natural to include docs here.
> Docs for `onCaughtError`, `onRecoverableError` and how to test error boundaries

- docs/react-testing-library/faq.mdx
You can see the issue on the current site by going to https://testing-library.com/docs/react-testing-library/faq and expanding the “How do I test error boundaries” section.
> Add missing code block terminator

- docs/dom-testing-library/api-configuration.mdx
As discussed with @MatanBobi  and @timdeschryver this is the documentation change to account for issue found with the `throwSuggestions` option when enforced.
For more context, this is discussed and related to issue [#1306 in dom-testing-library](https://github.com/testing-library/dom-testing-library/issues/1306).
- Go to [/docs/dom-testing-library/api-configuration/#throwsuggestions-experimental](https://deploy-preview-1425--testing-library.netlify.app/docs/dom-testing-library/api-configuration/#throwsuggestions-experimental)
- Read the newly added note in the throwSuggestions section.
> docs: add note for throwSuggestions issue #1306

- docs/qwik-testing-library/api.mdx
- docs/qwik-testing-library/example.mdx
- docs/qwik-testing-library/faq.mdx
- docs/qwik-testing-library/intro.mdx
- docs/qwik-testing-library/setup.mdx
- sidebars.js
This PR adds documentation for the new [Qwik Testing Library](https://github.com/ianlet/qwik-testing-library) to provide more testing tools for the Qwik Framework.
The library was tested with a few projects running in production, but any additional feedback is greatly appreciated as well!
We will keep updating the documentation with more examples and upcoming APIs (such as better mocking utilities and `renderHook`) when they become available.
_Note: the easy way to setup the library with `npm run qwik add testing-library` is a [PR in the Qwik framework](https://github.com/QwikDev/qwik/pull/6924) and will soon be available. You need to follow the manual setup for now._
> feat(qwik-testing-library): add documentation for Qwik Testing Library

- docs/qwik-testing-library/setup.mdx
@shairez made me realize the setup instructions were still mentioning `pnpm qwik add testing-library` as a quick way to setup the library even though it's not ready yet.
Let's just remove it and keep only the manual instructions for now. I'll make another PR to put it back once it's ready. Sorry about that! :pray:
> docs(qwik): adjust setup instructions

- docs/qwik-testing-library/intro.mdx
I forgot the qwik cli was also mentioned in the intro page. Let's remove it there as well as it's not ready yet.
> docs(qwik): remove qwik cli command from the intro

- src/css/custom.css
- src/pages/help.js
As per WCAG 2.0 guidelines, links must be visually distinguishable from normal text when they are in a text block without relying on color. This PR remediates that issue for the "Help" page.
Current Help Page in production: https://testing-library.com/help 
https://dequeuniversity.com/rules/axe/4.10/link-in-text-block?application=AxeChrome
https://www.w3.org/TR/WCAG20-TECHS/F73.html
> fix(a11y): underline links in a text block as pur WCAG 2.0

- docs/react-testing-library/setup.mdx
This PR adds a heading to the setup guide for `react-testing-library` that explains how to get auto-cleanup working when using Vitest. The wording was inspired by a similar heading in the `vue-testing-library` setup guide: https://testing-library.com/docs/vue-testing-library/setup/#vitest
> Add Vitest cleanup hint to react-testing-library setup docs

- sidebars.js
Match React Testing Library for better organization.
I noticed this today while I was reading through the Vue Testing Library docs for the first time, and noticed that the order of the docs in the sidebar was not the same as the React Testing Library docs that I look at all the time. I believe the order of the sidebar links should match across projects, and the rest of the projects and links do match as far as I can tell!
> docs: Update Vue Testing Library Sidebar Order

- docs/angular-testing-library/examples.mdx
- docs/bs-react-testing-library/examples.mdx
- docs/vue-testing-library/examples.mdx
- sidebars.js
Follow-up of #1459 to add more consistency in the sidebar and titles.
This PR:
- rearranges the sidebar to follow React's order
- rename "Examples" to "Example"
> use consistant naming in sidebar and titles

- docs/svelte-testing-library/setup.mdx
As I found out with my SvelteKit 5 project, we need to add `"types": ["@testing-library/jest-dom"]` to the `compilerOptions` in the project's `tsconfig.json`. Otherwise VSCode complains that it can't find e.g. `toBeInTheDocument` (Property 'toBeInTheDocument' does not exist on type 'Assertion<HTMLElement>'.ts(2339)).
I'm no TypeScript Pro, so feel free to reword what I wrote.  :-)
> Add missing documentation about using `@testing-library/jest-dom` with TypeScript

- docs/vue-testing-library/examples.mdx
On the React Testing Library Docs, there are TypeScript examples, but these do not exist on most other pages.
I believe that it's useful for TypeScript examples to exist on other pages as well, especially examples, and even if they're extremely similar to the JavaScript examples, because this makes it more accessible to newer developers.
Disclosure: I'm newer to VueJS and TypeScript (coming from JS/React), and have been reading the docs myself to get this set up on my end, so if anyone notices better ways of handling these examples I'm not attached to the code inside.
> Add TypeScript Examples to vue-testing-library

- docs/vue-testing-library/api.mdx
- docs/vue-testing-library/faq.mdx
This pull request updates several links on the Vue Testing Library API page.
Previously, these links for `@vue/test-utils` were directing users to the documentation site for Vue v2.x and earlier.  
Since today's Vue version is 3.x, I update these links to the `@vue/test-utils` documentation site for Vue 3.
> docs(Vue Testing Library): update `@vue/test-utils` link urls in api page to vue3
