website/pages/en/react.js

This fixes an Enzyme typo in the VS section

Typo in VS section

---

docs/example-input-event.md

Called out the user-event library in the input events documentation section

docs: updated the input events doc

---

docs/api-events.md

https://github.com/kentcdodds/dom-testing-library/pull/193

Add: a note about charCode defaults

---

website/siteConfig.js

Closes #3.
I just followed the docs [here](https://docusaurus.io/docs/en/search) and everything seems to be working.
Please let me know if you want to customize [the placeholder](https://docusaurus.io/docs/en/search#customizing-the-placeholder) or [the styling](https://community.algolia.com/docsearch/styling.html).

Add Algolia search

---

docs/api-queries.md
docs/react-testing-library/example-intro.md

Fix anchor link to getByLabelText

Fix anchor references in docs

---

docs/cypress-testing-library/intro.md

Fix broken link in Cypress examples

---

docs/install.md

document the published module

---

docs/api-async.md

So they show up on the subnav to the right

fix api/async headers

---

docs/guiding-principles.md

The structure of the sentence was somewhat confusing, and this change should help clarify the meaning.

Improve grammar of documentation

---

docs/dom-testing-library/api-queries.md
docs/dom-testing-library/cheatsheet.md
docs/react-testing-library/cheatsheet.md

docs: add note about throwing for multiple elements

---

docs/learning.md

Adding a new learning resource for developers to understand a point of view coming from years of experience with Enzyme going onto react-testing-library.

Learning Material - My Experience moving from Enzyme to react-testing-library

---

docs/dom-testing-library/faq.md
docs/vue-testing-library/faq.md
website/sidebars.json

Some of the questions I get asked most frequently when introducing VTL. 
I also fixed a broken (well, missing) link in DOM Testing FAQ section.
---
As usual, feel free to suggest any modification, idea, or suggestion 👍

Add FAQ section to Vue docs

---

docs/learning.md

https://twitter.com/kentcdodds/status/1135899506904461312

Add link to "How to Test Asynchronous Methods"

---

docs/ecosystem-user-event.md

Following https://github.com/testing-library/dom-testing-library/issues/260

Update link to user-event

---

docs/vue-testing-library/cheatsheet.md
docs/vue-testing-library/faq.md
website/sidebars.json

First I wanted to point to RTL' Cheatsheet page, but there are some nuances I wanted to highlight.
I also added a FAQ answer I thought it was already already there 😅

Add Cheatsheet page for VTL

---

docs/dom-testing-library/cheatsheet.md
docs/react-testing-library/cheatsheet.md

This PR add following API's to the document. 
- waitForDomChange
- waitForElementToBeRemoved
As I'm not English native please tell me if the description is odd.

Add some async API's to the cheatsheet

---

docs/react-testing-library/intro.md

Fix a typo

---

docs/dom-testing-library/api-queries.md

This PR:
- Fixes some typos
- Adds a word in a sentence to make it a bit clearer

Fix some typos

---

docs/example-react-modal.md
website/sidebars.json

Addresses #163 ,  so sorry for the delay here. 
Please let me know if there's anything I can do to improve!

add example modal test recipe

---

docs/dom-testing-library/example-intro.md

Changed `it's text` to `its text`.

Fix a minor typo

---

docs/dom-testing-library/example-intro.md
docs/example-reach-router.md
docs/example-react-context.md
docs/example-react-intl.md
docs/guide-disappearance.md
docs/marko-testing-library/api.md
docs/react-testing-library/api.md
docs/react-testing-library/example-intro.md
docs/react-testing-library/setup.md
docs/vue-testing-library/faq.md
package-lock.json

**Please Review**
update **all** references from _jest-dom/extend-expect_ to _@testing-library/jest-dom/extend-expect_

All contributors/edit agentkma

---

docs/dom-testing-library/api-helpers.md

For https://github.com/testing-library/testing-library-docs/issues/190

Remove doc for unsupported method

---

docs/react-testing-library/setup.md

add extra block for typescript users

docs: add typescript config update

---

docs/testcafe-testing-library/intro.md

update docs to support changes in @testing-library/testcafe 3.x

Update docs for testcafe 3.x

---

docs/react-testing-library/example-intro.md

added anonymous function to onClick call for fetchGreeting and passed in the url prop as an argument

all-contributors/example-function-agentkma

---

docs/vue-testing-library/examples.md

Fix broken links for vue-testing-library examples

---

docs/react-testing-library/faq.md

This is an attempt at writing up a response to [this question](https://github.com/testing-library/react-testing-library/issues/167). Happy to discuss variations of this answer.

Add initial FAQ response to what level to test react

---

docs/dom-testing-library/api-queries.md

Documentation for https://github.com/testing-library/dom-testing-library/pull/352
Preview: https://deploy-preview-266--testing-library.netlify.com/docs/dom-testing-library/api-queries#byrole

feat(queries): Add docs about byRole#hidden

---

docs/react-testing-library/setup.md

Hey,
There is a little change to remove an extra var.

Remove an unused var

---

docs/example-react-redux.md

Spelling Mistake

---

docs/svelte-testing-library/api.md
docs/svelte-testing-library/example.md
docs/svelte-testing-library/intro.md
website/sidebars.json

Updated the Svelte docs. Accidentally pushed to master branch of my fork hope that's not an issue.

docs: update svelte

---

docs/example-react-router.md

- `<Router>`  requires `history` prop
- `<LocationDisplay />` would not be updated when we call `window.history.pushState({}, '', route)`. Therefore, the test "rendering a component that uses withRouter" would fail.

Fix bug in code example of example-react-router.md

---

docs/react-testing-library/setup.md

Fix for https://github.com/testing-library/react-testing-library/issues/517

Add jest-environment-jsdom-fifteen recommendation

---

docs/example-react-modal.md

I just updated the modal example to use hooks, nothing much. It's the last example using a class component.

Fixing modal example to use hooks

---

docs/preact-testing-library/api.md

button -> buttonNode

---

docs/ecosystem-eslint-plugin-jest-dom.md
website/sidebars.json

Fixes #343
I wasn't sure where to put it in the sidebar so I put it under `eslint-plugin-testing-library`, but I could move it if preferred

docs: add eslint-plugin-jest-dom page

---

docs/angular-testing-library/api.md

- sort functions alphabetically
- add docs for new functions added to the Angular Testing Library

Update angular api

---

website/pages/en/support.js

Fix copy typo to buy course

---

docs/learning.md

Add my react-testing-library talk to learning.md

---

docs/dom-testing-library/api-configuration.md

Adding docs for this new config option.

add getElementError to configure documentation

---

docs/dom-testing-library/api-helpers.md

Fixes a small typo in the Helpers article.

docs(dom-testing-library): Fix typo

---

docs/dom-testing-library/api-async.md

@kentcdodds I updated the docs to reflect the `waitFor` change.  Not sure if I captured it the best, so lmk if we should tweak anything

update async docs to reflect changes in async helpers

---

docs/react-testing-library/setup.md

added React import statement because we are using JSX... otherwise, it was throwing an error:

fix: add React import statement

---

docs/angular-testing-library/examples.md

Add brackets around import { CounterComponent } from './counter.component.ts'

docs: Fix code example on angular examples.md

---

docs/react-testing-library/example-intro.md

Update example-intro to use the screen function

---

docs/dom-testing-library/api-events.md

Typo in api-events.md

---

docs/dom-testing-library/api-configuration.md

Docs PR for: https://github.com/testing-library/dom-testing-library/pull/542

add config option

---

docs/ecosystem-user-event.md

Add async to test method since it uses await on `userEvent.type(...)`

fix: add async to test method

---

docs/dom-testing-library/api-queries.md

https://github.com/testing-library/testing-library-docs/blob/ea15db89abea14f4710ea6c7484884592a1b37a8/docs/dom-testing-library/api-configuration.md#L18-L19

docs: fix default hidden option value for getByRole query

---

docs/dom-testing-library/api-configuration.md

fixed newline issue on config page

fixed newline issue on config page

---

docs/example-drag.md

docs: Add drag example to recipes

---

docs/dom-testing-library/install.md

Update `Wrappers` section with others libs defined in sidebar

docs: Update install.md / add missed wrappers

---

docs/dom-testing-library/api-async.md

https://github.com/testing-library/dom-testing-library/pull/671

add onTimeout

---

docs/learning.md

- Adds both Portuguese and English version of my React Hooks broke my tests, now what? talk
- it approaches a migration from enzyme to react testing library and does a dive into the fundamentals to use the React Testing Library

Add React Hooks broke my tests, now what? EN and PT talk

---

docs/react-testing-library/api.md

Add a recommendation on how to import `act`

---

docs/react-testing-library/example-intro.md

Few minor things were missing when I was trying out.

minor fixes in example-intro.md

---

docs/react-testing-library/example-intro.md

fix(reactExampleIntro): Missing initialState for useReducer

---

docs/ecosystem-user-event.md

Explanation: https://github.com/testing-library/user-event/issues/429#issuecomment-679856884

Fix failing user-event example

---

docs/dom-testing-library/api-async.md

https://github.com/testing-library/testing-library-docs/issues/619

api-async: warn flaky with expect dot assertions

---

website/pages/en/index.js

checking deploy preview to see how it looks

shorten adapter names to remove line wraps

---

docs/example-input-event.md

migrate example-input-event recipe to use hooks

---

docs/dom-testing-library/api-async.md

Ref: https://github.com/testing-library/dom-testing-library/pull/782

add promise support to waitFor

---

docs/example-react-transition-group.md

Migrate react transition group recipe to hooks

---

docs/example-react-router.md

Might be partially related to #589

Add missing useLocation import

---

docs/dom-testing-library/api-events.mdx

Added fireEvent to the import in the example

docs: Added fireEvent to the import in the example

---

docs/example-react-intl.mdx

Update format.js link on [`react-intl` docs](https://testing-library.com/docs/example-react-intl/) example according to #662

fix: update format.js link

---

docs/preact-testing-library/api.mdx

[docs] fix typo for preact-api docs

---

docs/react-testing-library/example-intro.mdx

Add anonymous function with fetchUrl call and pass the url prop in React Testing Library example
Closes #220

docs(example-intro): add anonymous function with fetchUrl 

---

docs/react-testing-library/api.mdx
docs/vue-testing-library/api.mdx

fix: broken links in api for react and vue

---

docs/example-codesandbox.mdx

Whoops 😅
I just automated updating all my branches and things like this pop up here and there...

update branch to main

---

docs/queries/about.mdx

updated the "advanced" regex comment to be more helpful to a new reader

docs: Explain what the "advanced regex" does

---

docs/dom-testing-library/api-custom-queries.mdx
docs/dom-testing-library/cheatsheet.mdx
docs/react-testing-library/setup.mdx
docs/vue-testing-library/cheatsheet.mdx

fix: broken links in multiple pages

---

docs/webdriverio-testing-library/intro.mdx
sidebars.js

I wasn't sure about the process around this but figured opening a PR was a good start.
This is a first draft of an intro page for [webdriverio-testing-library](https://github.com/testing-library/webdriverio-testing-library). I tried to keep the structure similar to the docs for other frameworks.
Any edits/suggestions would be much appreciated! 😄

docs: add webdriverio-testing-library intro

---

docs/ecosystem-jest-native.mdx
docs/example-findByText.md

chore(docs): remove bad example

---

docs/ecosystem-user-event.mdx

Update to special character commands to correct camel case format.

docs(user-event): Fix special character casing

---

docs/queries/bytext.mdx

Doc page:
https://testing-library.com/docs/queries/bytext#ignore
api:
https://testing-library.com/docs/queries/bytext#api

docs: Correct the ignore option default value

---

docs/guides-using-fake-timers.mdx

I believe the changes would help improve readability.

doc: add spacing between paragraphs

---

docs/ecosystem-user-event.mdx

Doc: https://testing-library.com/docs/ecosystem-user-event/#api

docs: Correct meaning and punctuation of sentence

---

docs/react-testing-library/migrate-from-enzyme.mdx

resolves https://github.com/testing-library/testing-library-docs/issues/803

docs: replaced url for queries page

---

docs/example-formik.md

This reverts commit e8524e8f30fc5af7a586ec6b3fa1ed8c9ab62f88.
Closes https://github.com/testing-library/testing-library-docs/pull/872
We don't expose the formik bag in the demo so we don't need to assert on it. 
/cc @houcoder

Revert "Update example-formik.md (#692)"

---

docs/learning.mdx

Miguel Angel Duran aka Midudev is one of the best professors in Spanish. In this video, he splains the basics of the Testing Library. This video is part of his free React course.

Adding spanish tutorial made by Miguel Angel Duran

---

docs/learning.mdx

I wrote an article using Angular Testing Library

docs: update learning.mdx

---

docs/intro.mdx

- Add full stop to end of sentence
Just fixing up a small problem with this PR.

docs: add full stop to end of sentence

---

docs/learning.mdx

I hadn't seen any good tutorials on setting up Apollo with react-testing-library so I wrote one :)

docs: add article for testing Apollo client components

---

README.md

docs: remove Open Collective badge

---

src/css/custom.css

Resolves https://github.com/testing-library/testing-library-docs/issues/1022

fix: adjust width correctly to prevent overflow

---

docs/example-react-intl.mdx

This PR fixes some minor typos in the doc.

docs: fix minor typos

---

docs/learning.mdx

Add a link to the article 'Good testing practices with 🦔 Angular Testing Library' in  Spanish.

Add article testing library

---

docs/react-testing-library/setup.mdx

Added children type to fix a potential TS error

Add children type to fix ts error

---

docs/ecosystem-user-event.mdx

Resolve: https://github.com/testing-library/testing-library-docs/issues/912

docs: fix the user-event example

---

docs/example-react-router.mdx

This PR addresses the issue https://github.com/testing-library/testing-library-docs/issues/1110.

docs: use correct react router v5 api in example

---

docs/svelte-testing-library/setup.mdx

Fixed incorrect vitest config file
check -> [vitest docs](https://vitest.dev/guide/#configuring-vitest)

docs(svelte): fix vitest config file

---

docs/user-event/api-keyboard.mdx

user-event: Update api-keyboard.mdx

---

docs/recipes.mdx

Fixed the routing issue in the [About the Examples](https://testing-library.com/docs/recipes) page.

docs: update the router links in recipes.mdx

---

docs/dom-testing-library/api-events.mdx

Updating keycode reference site as https://keycode.info/ no worky

Docs: Update keycode reference site

---

docs/learning.mdx

I've written extensively about using RTL in different contexts and think these articles will be good resources for working with the library.

Add articles to the "Learning material" section

---

docs/learning.mdx

#1277 add Angular challenges on testing inside the learning material page of Testing library documentation

add angular challenges to learning material page

---

docs/svelte-testing-library/setup.mdx

Update setup.mdx - small grammar fix

---

docs/queries/byrole.mdx

from https://github.com/testing-library/dom-testing-library/issues/1128

docs(byrole.mdx): add tips for input type password

---

docs/react-testing-library/api.mdx
docs/react-testing-library/faq.mdx

This PR reverts #1417
cc @eps1lon

revert: #11ffbf365222eeb348cc14345fffd88fca6855f9

---

docs/example-external.mdx

docs: remove example external link

---

docs/react-testing-library/faq.mdx

Some of the FAQ content is missing due to this typo.

Update faq.mdx - fix code block and formatting
